/* eslint-disable react-hooks/set-state-in-effect */
import { useCallback, useEffect, useMemo, useState } from "react";
import { Pressable, View } from "react-native";
import { router } from "expo-router";
import { Avatar } from "../components/Avatar";
import { TrainerAgenda } from "../components/TrainerAgenda";
import { Button, Card, Heading, Icon, Notice, Page, Pill, Row, Txt } from "../components/ui";
import { CoachingRelationship } from "../services/community";
import { TrainerAttention, TrainerClientSummary, TrainerDashboard, attentionForClient, median, priorityClients, trainerImpact } from "../logic/trainerWorkspace";
import { useCommunity } from "../state/Community";
import { useTheme } from "../theme";

type WorkspaceSection = "agenda" | "today" | "clients" | "impact";
const attentionCopy: Record<TrainerAttention, { title: string; detail: string }> = {
  "on-track": { title: "Al día", detail: "Todo sigue el plan." }, "routine-pending": { title: "Plan pendiente", detail: "Hay cambios por revisar." }, inactive: { title: "Sin actividad", detail: "Conviene comprobar cómo está." }, "needs-review": { title: "Necesita atención", detail: "La adherencia reciente pide intervención." },
};
const toDashboard = (relationships: CoachingRelationship[]): TrainerDashboard => {
  const clients = relationships.filter(item => item.status === "active" && item.role === "trainer").map(item => {
    const resolved: TrainerClientSummary = { relationshipId: item.id, id: item.person.id, name: item.person.name, handle: item.person.handle, avatar: item.person.avatar, activeSince: item.acceptedAt ?? item.updated, routineStatus: "none", adherence: null, strengthPercent: null, attention: "on-track" };
    return { ...resolved, attention: attentionForClient(resolved) };
  });
  return { activeClients: clients.length, pendingRequests: relationships.filter(item => item.status === "pending" && item.role === "trainer").length, routinesPending: clients.filter(item => item.routineStatus === "sent" || item.routineStatus === "draft").length, needsAttention: clients.filter(item => item.attention !== "on-track").length, medianAdherence: median(clients.map(item => item.adherence)), medianStrengthChange: median(clients.map(item => item.strengthPercent)), eligibleClients: clients.length, sampleSufficient: clients.length >= 5, clients };
};

export default function Trainer() {
  const { user, request } = useCommunity(); const { colors } = useTheme();
  const [dashboard, setDashboard] = useState<TrainerDashboard | null>(null); const [requests, setRequests] = useState<CoachingRelationship[]>([]); const [section, setSection] = useState<WorkspaceSection>("agenda"); const [filter, setFilter] = useState<"all" | "attention">("all"); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { if (!user?.trainerEnabled) return; setBusy(true); setError(""); try { setDashboard(await request<TrainerDashboard>("/trainer/dashboard")); setRequests(await request<CoachingRelationship[]>("/trainer/requests")); } catch { try { const relationships = await request<CoachingRelationship[]>("/coaching"); setDashboard(toDashboard(relationships)); setRequests(relationships.filter(item => item.status === "pending" && item.role === "trainer")); } catch (reason) { setError((reason as Error).message); } } finally { setBusy(false); } }, [request, user?.trainerEnabled]);
  useEffect(() => { void load(); }, [load]);
  const queue = useMemo(() => priorityClients((dashboard?.clients ?? []).filter(client => client.attention !== "on-track")), [dashboard]); const clients = useMemo(() => priorityClients((dashboard?.clients ?? []).filter(client => filter === "all" || client.attention !== "on-track")), [dashboard, filter]); const impact = useMemo(() => dashboard ? trainerImpact(dashboard) : null, [dashboard]);
  const openClient = (client: TrainerClientSummary, target?: "calendar") => router.push({ pathname: "/trainer-client" as never, params: { relationship: client.relationshipId, from: "trainer", ...(target ? { section: target } : {}) } } as never);
  const respond = async (item: CoachingRelationship, action: "accept" | "decline") => { setBusy(true); try { await request(`/trainer/requests/${item.id}`, "PATCH", { action }); await load(); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  if (!user?.trainerEnabled) return <Page><Heading eyebrow="Espacio profesional" title="Activa tu perfil de entrenador" subtitle="Cuando actives Ofrezco entrenamiento en tu Perfil, aquí tendrás tus deportistas, solicitudes y planes." /><Button label="Ir a mi perfil" tone="green" variant="secondary" icon="user" onPress={() => router.push("/profile")} /></Page>;
  return <Page><Row style={{ justifyContent: "space-between", gap: 12 }}><View style={{ flex: 1 }}><Heading eyebrow="ESPACIO PROFESIONAL · PRUEBA" title="Entrenador" subtitle="Prioriza tu seguimiento y acompaña mejor." /></View><Button label="Perfil profesional" compact variant="ghost" icon="user" onPress={() => router.push("/community")} /></Row>{!!error && <Notice error>{error}</Notice>}
    <Row style={{ gap: 7, flexWrap: "wrap" }}>{([ ["agenda", "Agenda", "calendar"], ["today", "Hoy", "sun"], ["clients", "Clientes", "users"], ["impact", "Impacto", "award"] ] as const).map(([id, label, icon]) => <Button key={id} compact label={label} icon={icon} variant={section === id ? "primary" : "secondary"} onPress={() => setSection(id)} />)}</Row>
    {section === "agenda" && <View style={{ gap: 12 }}><Card style={{ gap: 8, backgroundColor: colors.accentSoft }}><Txt weight="600" size={20}>Seguimiento sin ruido</Txt><Txt muted>La Agenda reúne el plan y las alertas que requieren tu intervención.</Txt><Pill>{queue.length ? `${queue.length} prioridades` : "Todo al día"}</Pill></Card><TrainerAgenda clients={dashboard?.clients ?? []} onOpenClient={(client, target) => openClient(client, target)} /></View>}
    {section === "today" && <View style={{ gap: 9 }}><Card style={{ gap: 10, backgroundColor: colors.accentSoft }}><Txt weight="600" size={20}>Tu foco de hoy</Txt><Row style={{ flexWrap: "wrap", gap: 10 }}><Txt>Deportistas activos: {dashboard?.activeClients ?? 0}</Txt><Txt>Necesitan atención: {dashboard?.needsAttention ?? 0}</Txt><Txt>Planes pendientes: {dashboard?.routinesPending ?? 0}</Txt></Row></Card>{queue.length ? queue.slice(0, 4).map(client => <Pressable key={client.relationshipId} onPress={() => openClient(client)}><Card><Row style={{ gap: 10, alignItems: "center" }}><Avatar id={client.avatar} size={42} /><View style={{ flex: 1 }}><Txt weight="600" translate={false}>{client.name}</Txt><Txt muted size={12}>{attentionCopy[client.attention].detail}</Txt></View><Icon name="chevron-right" size={19} /></Row></Card></Pressable>) : <Card><Txt weight="600">No hay nada urgente</Txt><Txt muted>Los planes y el seguimiento están al día.</Txt></Card>}</View>}
    {section === "clients" && <View style={{ gap: 9 }}><Row style={{ justifyContent: "space-between" }}><View><Txt weight="600" size={20}>Mis deportistas</Txt><Txt muted size={12}>Abre un expediente para mantener el contexto.</Txt></View><Row><Button label="Todos" compact variant={filter === "all" ? "primary" : "ghost"} onPress={() => setFilter("all")} /><Button label="Atención" compact variant={filter === "attention" ? "primary" : "ghost"} onPress={() => setFilter("attention")} /></Row></Row>{clients.map(client => <Pressable key={client.relationshipId} accessibilityRole="button" accessibilityLabel={`Abrir a ${client.name}`} onPress={() => openClient(client)}><Card><Row style={{ gap: 11, alignItems: "center" }}><Avatar id={client.avatar} size={48} /><View style={{ flex: 1 }}><Txt weight="600" translate={false}>{client.name}</Txt><Txt muted size={12}>Adherencia: {client.adherence ?? "—"}% · Fuerza: {client.strengthPercent === null || client.strengthPercent === undefined ? "—" : `${client.strengthPercent >= 0 ? "+" : ""}${client.strengthPercent}%`}</Txt></View><Icon name="chevron-right" size={20} /></Row></Card></Pressable>)}</View>}
    {section === "impact" && impact && <Card style={{ gap: 8 }}><Txt weight="600" size={20}>Impacto</Txt><Txt muted>Resultados agregados del seguimiento activo.</Txt><Txt>Adherencia mediana: {impact.adherence ?? "—"}%</Txt><Txt>Mejora de fuerza: {impact.strength === null ? "—" : `${impact.strength >= 0 ? "+" : ""}${impact.strength}%`}</Txt></Card>}
    {!!requests.length && <Card style={{ gap: 8 }}><Txt weight="600">Solicitudes</Txt>{requests.map(item => <Row key={item.id}><Txt style={{ flex: 1 }} translate={false}>{item.person.name}</Txt><Button label="Aceptar" compact onPress={() => void respond(item, "accept")} /><Button label="Rechazar" compact variant="ghost" onPress={() => void respond(item, "decline")} /></Row>)}</Card>}
    <Button label={busy ? "Actualizando…" : "Actualizar"} compact variant="ghost" icon="refresh-cw" disabled={busy} onPress={() => void load()} />
  </Page>;
}
