import { useEffect, useState } from "react";
import { useCommunity } from "../state/Community";
import { TrainerProfile, TrainerReview } from "../services/community";
import { Button, Card, Field, Notice, Row, Txt } from "./ui";

const blank: TrainerProfile = { public: false, specialties: [], modalities: [], experienceYears: 0, credentials: "", availability: "", pricing: "", statsPublic: false };
export function TrainerProfileCard({ profileId, mine }: { profileId: string; mine: boolean }) {
  const { request } = useCommunity(); const [profile, setProfile] = useState<TrainerProfile>(blank); const [editing, setEditing] = useState(false); const [specialties, setSpecialties] = useState(""); const [modalities, setModalities] = useState(""); const [reviews, setReviews] = useState<TrainerReview[]>([]); const [error, setError] = useState(""); const [rating, setRating] = useState(5); const [reviewBody, setReviewBody] = useState("");
  const load = () => { void Promise.all([request<TrainerProfile>(`/profiles/${profileId}/trainer`), request<{ reviews: TrainerReview[] }>(`/profiles/${profileId}/reviews`)]).then(([p, r]) => { setProfile(p); setSpecialties(p.specialties.join(", ")); setModalities(p.modalities.join(", ")); setReviews(r.reviews); }).catch(error => { if (mine) { setProfile(blank); } else setError(error.message); }); };
  useEffect(load, [profileId]);
  const save = () => void request<TrainerProfile>("/me/trainer-profile", "PUT", { ...profile, specialties: specialties.split(",").map(value => value.trim()).filter(Boolean), modalities: modalities.split(",").map(value => value.trim()).filter(Boolean) }).then(value => { setProfile(value); setEditing(false); }).catch(error => setError(error.message));
  if (!mine && !profile.updated) return null;
  return <Card><Row style={{ justifyContent: "space-between" }}><Txt weight="600" size={19}>Perfil profesional</Txt><Txt style={{ color: "#1B7A42" }} weight="600">Entrenador</Txt></Row>
    {editing ? <><Field label="Especialidades (separadas por comas)" value={specialties} onChangeText={setSpecialties} maxLength={320} /><Field label="Modalidades" value={modalities} onChangeText={setModalities} maxLength={120} /><Field label="Años de experiencia" value={String(profile.experienceYears)} onChangeText={value => setProfile(current => ({ ...current, experienceYears: Number(value) || 0 }))} numeric /><Field label="Credenciales" value={profile.credentials} onChangeText={value => setProfile(current => ({ ...current, credentials: value }))} multiline maxLength={500} /><Field label="Disponibilidad" value={profile.availability} onChangeText={value => setProfile(current => ({ ...current, availability: value }))} maxLength={160} /><Field label="Tarifas o contacto" value={profile.pricing} onChangeText={value => setProfile(current => ({ ...current, pricing: value }))} maxLength={160} /><Row><Button label={profile.public ? "Perfil público" : "Perfil privado"} compact variant={profile.public ? "primary" : "secondary"} onPress={() => setProfile(current => ({ ...current, public: !current.public }))} /><Button label={profile.statsPublic ? "Estadísticas públicas" : "Estadísticas privadas"} compact variant={profile.statsPublic ? "primary" : "secondary"} onPress={() => setProfile(current => ({ ...current, statsPublic: !current.statsPublic }))} /></Row><Button label="Guardar perfil profesional" onPress={save} /></> : <><Txt>{profile.specialties.join(" · ") || "Especialidades por definir"}</Txt><Txt muted>{profile.modalities.join(" · ")}</Txt><Txt muted>{profile.experienceYears ? `${profile.experienceYears} años de experiencia` : "Experiencia no indicada"}</Txt>{!!profile.credentials && <Txt translate={false}>{profile.credentials}</Txt>}{!!profile.availability && <Txt muted translate={false}>{profile.availability}</Txt>}{!!profile.pricing && <Txt muted translate={false}>{profile.pricing}</Txt>}{profile.stats && <Card style={{ padding: 12 }}><Txt weight="600">Resultados agregados en Akhyles</Txt><Txt>{profile.stats.clientsActive} clientes activos · {profile.stats.clientsSupported} gestionados</Txt>{profile.stats.sampleSufficient ? <Txt>{profile.stats.averageSessions90Days} sesiones medias / 90 días · {profile.stats.consistencyRate}% con constancia</Txt> : <Txt muted>Necesita al menos 5 clientes que hayan dado consentimiento para mostrar métricas de progreso.</Txt>}</Card>}{mine && <Button label="Editar perfil profesional" compact variant="secondary" onPress={() => setEditing(true)} />}</>}
    {!mine && <><Txt weight="600">Valora una colaboración activa</Txt><Row>{[1, 2, 3, 4, 5].map(value => <Button key={value} label={`${value} ★`} compact variant={rating === value ? "primary" : "secondary"} onPress={() => setRating(value)} />)}</Row><Field label="Reseña verificada" value={reviewBody} onChangeText={setReviewBody} multiline maxLength={800} placeholder="Cuenta cómo ha sido el seguimiento" /><Button label="Publicar reseña" compact variant="secondary" onPress={() => void request(`/profiles/${profileId}/reviews`, "PUT", { rating, communication: rating, adaptation: rating, followUp: rating, body: reviewBody }).then(load).catch(error => setError(error.message))} /></>}
    {!!reviews.length && <><Txt weight="600">Reseñas verificadas · {reviews.length}</Txt>{reviews.slice(0, 3).map(review => <Txt key={review.id} translate={false}>{"★".repeat(review.rating)} · @{review.author.handle}{review.body ? ` — ${review.body}` : ""}</Txt>)}</>}{!!error && <Notice error>{error}</Notice>}
  </Card>;
}
