<?php
declare(strict_types=1);
namespace Akhyles;

/** First-party Community data. Account identity is the only authentication. */
final class Community {
    public function __construct(private \PDO $db) { $db->setAttribute(\PDO::ATTR_ERRMODE,\PDO::ERRMODE_EXCEPTION);$db->setAttribute(\PDO::ATTR_DEFAULT_FETCH_MODE,\PDO::FETCH_ASSOC);$this->migrate(); }
    private function migrate(): void { foreach([
        'CREATE TABLE IF NOT EXISTS community_follows (follower_id VARCHAR(64) NOT NULL,followed_id VARCHAR(64) NOT NULL,created BIGINT NOT NULL,PRIMARY KEY(follower_id,followed_id),INDEX(followed_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS community_notifications (id CHAR(32) PRIMARY KEY,recipient_id VARCHAR(64) NOT NULL,actor_id VARCHAR(64) NOT NULL,type VARCHAR(32) NOT NULL,created BIGINT NOT NULL,read_at BIGINT NULL,UNIQUE KEY notification_once(recipient_id,actor_id,type),INDEX notification_recipient(recipient_id,read_at,created)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS community_blocks (user_id VARCHAR(64) NOT NULL,blocked_id VARCHAR(64) NOT NULL,created BIGINT NOT NULL,PRIMARY KEY(user_id,blocked_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS community_posts (id CHAR(32) PRIMARY KEY,user_id VARCHAR(64) NOT NULL,caption VARCHAR(500) NOT NULL,created BIGINT NOT NULL,INDEX(created),INDEX(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS community_post_likes (post_id CHAR(32) NOT NULL,user_id VARCHAR(64) NOT NULL,created BIGINT NOT NULL,PRIMARY KEY(post_id,user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS community_reports (id CHAR(32) PRIMARY KEY,reporter_id VARCHAR(64) NOT NULL,target_type VARCHAR(16) NOT NULL,target_id VARCHAR(64) NOT NULL,reason VARCHAR(500) NOT NULL,created BIGINT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS community_gyms (id CHAR(32) PRIMARY KEY,name VARCHAR(120) NOT NULL,city VARCHAR(120) NOT NULL DEFAULT \'\',created BIGINT NOT NULL,UNIQUE KEY gym_name_city(name,city)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS community_coaching (id CHAR(32) PRIMARY KEY,client_id VARCHAR(64) NOT NULL,trainer_id VARCHAR(64) NOT NULL,status VARCHAR(16) NOT NULL,created BIGINT NOT NULL,updated BIGINT NOT NULL,UNIQUE KEY coaching_pair(client_id,trainer_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS community_coaching_routines (coaching_id CHAR(32) PRIMARY KEY,payload MEDIUMTEXT NOT NULL,revision INT NOT NULL DEFAULT 1,updated BIGINT NOT NULL,author_id VARCHAR(64) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4'
    ] as $sql)$this->db->exec($sql);try{$this->db->exec('ALTER TABLE community_profiles ADD COLUMN trainer_enabled TINYINT NOT NULL DEFAULT 0');}catch(\PDOException){} }
    private function q(string $sql,array $v=[]): \PDOStatement{$s=$this->db->prepare($sql);$s->execute($v);return $s;}
    private function bad(int $code,string $text):never{throw new ApiError($code,$text);} private function id():string{return bin2hex(random_bytes(16));}
    private function txt(mixed $v,int $max,bool $required=false):string{if(!is_string($v)||mb_strlen($v,'UTF-8')>$max)$this->bad(400,'Revisa los campos indicados.');$v=trim($v);if($required&&$v==='')$this->bad(400,'Revisa los campos indicados.');return $v;}
    /** Stable comparison key: casing, accents, punctuation and repeated spaces never create another gym. */
    private function gymKey(string $value):string{$value=trim(mb_strtolower($value,'UTF-8'));$plain=iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$value);if($plain!==false)$value=$plain;$value=preg_replace('/[^a-z0-9]+/',' ',$value)??'';return trim(preg_replace('/\s+/',' ',$value)??'');}
    private function yes(mixed $v):bool{if(!is_bool($v))$this->bad(400,'Revisa las opciones de privacidad.');return $v;}
    private function profile(string $id,string $name):array{$p=$this->q('SELECT * FROM community_profiles WHERE user_id=?',[$id])->fetch();if($p)return $p;$handle='akh_'.substr($id,0,16);$this->q('INSERT INTO community_profiles(user_id,handle,name,created)VALUES(?,?,?,?)',[$id,$handle,mb_strcut($name?:'Atleta',0,80,'UTF-8'),time()]);return $this->q('SELECT * FROM community_profiles WHERE user_id=?',[$id])->fetch();}
    private function existing(string $id):array{$p=$this->q('SELECT * FROM community_profiles WHERE user_id=?',[$id])->fetch();if(!$p)$this->bad(404,'Perfil no encontrado.');return $p;}
    private function following(string $a,string $b):bool{return(bool)$this->q('SELECT 1 FROM community_follows WHERE follower_id=? AND followed_id=?',[$a,$b])->fetchColumn();}
    private function connected(string $a,string $b):bool{return $this->following($a,$b)&&$this->following($b,$a);}
    private function blocked(string $a,string $b):bool{return(bool)$this->q('SELECT 1 FROM community_blocks WHERE (user_id=? AND blocked_id=?) OR (user_id=? AND blocked_id=?)',[$a,$b,$b,$a])->fetchColumn();}
    private function view(array $p,string $who):array{$id=$p['user_id'];$self=$id===$who;$following=$self?false:$this->following($who,$id);$followsYou=$self?false:$this->following($id,$who);$friends=$self||($following&&$followsYou);$routine=(bool)$this->q('SELECT 1 FROM community_routines WHERE user_id=?',[$id])->fetchColumn();$progress=(bool)$this->q('SELECT 1 FROM community_progress WHERE user_id=?',[$id])->fetchColumn();return ['id'=>$id,'handle'=>$p['handle'],'name'=>$p['name'],'bio'=>$p['bio'],'avatar'=>$p['avatar'],'level'=>$p['level'],'posts'=>(int)$this->q('SELECT COUNT(*) FROM community_posts WHERE user_id=?',[$id])->fetchColumn(),'followers'=>(int)$this->q('SELECT COUNT(*) FROM community_follows WHERE followed_id=?',[$id])->fetchColumn(),'following'=>(int)$this->q('SELECT COUNT(*) FROM community_follows WHERE follower_id=?',[$id])->fetchColumn(),'followed'=>$following,'followsYou'=>$followsYou,'connected'=>$friends,'trainerEnabled'=>(bool)($p['trainer_enabled']??false),'routineId'=>$routine&&($self||(bool)$p['routine_public']||$friends)?$id:null,'progressVisible'=>$progress&&($self||$p['progress_visibility']==='public'||($p['progress_visibility']==='friends'&&$friends)),'trainingPlace'=>$p['training_place'],'city'=>$p['city'],'routinePublic'=>(bool)$p['routine_public'],'progressPublic'=>$p['progress_visibility']!=='private','progressVisibility'=>$p['progress_visibility'],'detailsPublic'=>(bool)$p['details_public'],'bodyWeightPublic'=>(bool)$p['body_weight_public'],'rankingPublic'=>(bool)$p['ranking_public']];}
    private function post(array $r,string $who):array{return['id'=>$r['id'],'userId'=>$r['user_id'],'handle'=>$r['handle'],'name'=>$r['name'],'caption'=>$r['caption'],'created'=>gmdate('c',(int)$r['created']),'likes'=>(int)$r['likes'],'liked'=>(bool)$this->q('SELECT 1 FROM community_post_likes WHERE post_id=? AND user_id=?',[$r['id'],$who])->fetchColumn()];}
    private function coach(string $id,string $who):array{$r=$this->q('SELECT * FROM community_coaching WHERE id=? AND (client_id=? OR trainer_id=?)',[$id,$who,$who])->fetch();if(!$r)$this->bad(404,'Colaboración no disponible.');return $r;}
    private function board(string $who,string $scope,int $offset,array $me):array{if(!in_array($scope,['friends','global','gym'],true))$this->bad(400,'Clasificación no válida.');if($scope==='gym'&&!$me['training_place'])return['entries'=>[],'next'=>null,'total'=>0,'me'=>null,'nextRival'=>null,'gap'=>null,'needsLocation'=>true,'location'=>''];$all=[];foreach($this->q('SELECT p.*,g.payload FROM community_profiles p JOIN community_progress g ON g.user_id=p.user_id WHERE p.ranking_public=1')->fetchAll() as $p){if($this->blocked($who,$p['user_id']))continue;if($scope==='friends'&&$p['user_id']!==$who&&!$this->connected($who,$p['user_id']))continue;if($scope==='gym'&&$this->gymKey($p['training_place'])!==$this->gymKey($me['training_place']))continue;$d=json_decode($p['payload'],true);if(!is_array($d)||empty($d['pointsRankingEligible'])||!is_numeric($d['points']??null))continue;$all[]=['id'=>$p['user_id'],'handle'=>$p['handle'],'name'=>$p['name'],'avatar'=>$p['avatar'],'points'=>(float)$d['points'],'coverage'=>(int)($d['pointsCoverage']??0),'reliability'=>(int)($d['pointsReliability']??0)];}usort($all,fn($a,$b)=>$b['points']<=>$a['points']?:strcmp($a['handle'],$b['handle']));foreach($all as $i=>&$e)$e['rank']=$i+1;unset($e);$mine=array_values(array_filter($all,fn($e)=>$e['id']===$who))[0]??null;$rival=$mine?$all[$mine['rank']]??null:null;return['entries'=>array_slice($all,$offset,20),'next'=>$offset+20<count($all)?$offset+20:null,'total'=>count($all),'me'=>$mine,'nextRival'=>$rival,'gap'=>$mine&&$rival?round($rival['points']-$mine['points'],1):null,'needsLocation'=>false,'location'=>$scope==='gym'?$me['training_place']:''];}
    public function handle(string $method,string $path,array $data,array $principal):array{
        if($path==='/health'&&$method==='GET')return['service'=>'akhyles-community','ok'=>true,'identity'=>'akhyles-account'];$who=$principal['id'];$mine=$this->profile($who,$principal['name']);
        if($path==='/me'&&$method==='GET')return $this->view($mine,$who);
        if($path==='/me'&&$method==='PATCH'&&array_key_exists('trainerEnabled',$data))$this->q('UPDATE community_profiles SET trainer_enabled=? WHERE user_id=?',[$this->yes($data['trainerEnabled']),$who]);
        if($path==='/me'&&$method==='PATCH'){ $name=$this->txt($data['name']??$mine['name'],80,true);$handle=strtolower(ltrim($this->txt($data['handle']??$mine['handle'],24,true),'@'));if(!preg_match('/^[a-z0-9_]{3,24}$/',$handle))$this->bad(400,'El @ debe tener 3–24 caracteres: letras, números o _.');$level=$data['level']??$mine['level'];if(!in_array($level,['beginner','intermediate','advanced'],true))$this->bad(400,'Revisa tu nivel.');try{$this->q('UPDATE community_profiles SET handle=?,name=?,bio=?,level=?,avatar=?,training_place=?,city=? WHERE user_id=?',[$handle,$name,$this->txt($data['bio']??$mine['bio'],500),$level,$this->txt($data['avatar']??$mine['avatar'],64),$this->txt($data['trainingPlace']??$mine['training_place'],120),$this->txt($data['city']??$mine['city'],120),$who]);}catch(\PDOException){$this->bad(409,'Ese @ ya está registrado.');}return $this->view($this->profile($who,$name),$who);}
        if($path==='/me/privacy'&&$method==='PATCH'){$routine=array_key_exists('routinePublic',$data)?$this->yes($data['routinePublic']):(bool)$mine['routine_public'];$details=array_key_exists('detailsPublic',$data)?$this->yes($data['detailsPublic']):(bool)$mine['details_public'];$weight=array_key_exists('bodyWeightPublic',$data)?$this->yes($data['bodyWeightPublic']):(bool)$mine['body_weight_public'];$ranking=array_key_exists('rankingPublic',$data)?$this->yes($data['rankingPublic']):(bool)$mine['ranking_public'];$visibility=$data['progressVisibility']??(($data['progressPublic']??null)===false?'private':$mine['progress_visibility']);if(!in_array($visibility,['private','friends','public'],true))$this->bad(400,'Revisa las opciones de privacidad.');$this->q('UPDATE community_profiles SET routine_public=?,progress_visibility=?,details_public=?,body_weight_public=?,ranking_public=? WHERE user_id=?',[$routine,$visibility,$details,$weight,$ranking,$who]);return $this->view($this->profile($who,''),$who);}
        if(in_array($path,['/routines/me','/progress/me'],true)&&in_array($method,['PUT','DELETE'],true)){$table=$path==='/routines/me'?'community_routines':'community_progress';if($method==='DELETE'){$this->q("DELETE FROM $table WHERE user_id=?",[$who]);return['ok'=>true];}$this->q("INSERT INTO $table(user_id,payload,updated)VALUES(?,?,?) ON DUPLICATE KEY UPDATE payload=VALUES(payload),updated=VALUES(updated)",[$who,json_encode($data,JSON_UNESCAPED_UNICODE),gmdate('c')]);return['ok'=>true];}
        if($path==='/comparison'&&in_array($method,['POST','DELETE'],true)){if($method==='DELETE'){$this->q('DELETE FROM community_samples WHERE user_id=?',[$who]);return['ok'=>true];}$this->q('INSERT INTO community_samples(user_id,payload,updated)VALUES(?,?,?) ON DUPLICATE KEY UPDATE payload=VALUES(payload),updated=VALUES(updated)',[$who,json_encode($data,JSON_UNESCAPED_UNICODE),time()]);$peers=(int)$this->q('SELECT COUNT(*) FROM community_samples WHERE user_id<>?',[$who])->fetchColumn();return['status'=>$peers?'available':'insufficient','peers'=>$peers,'rate'=>null,'exercises'=>0];}
        if($path==='/profiles'&&$method==='GET'){$s=trim((string)($_GET['q']??''));$sql='SELECT * FROM community_profiles';$args=[];if($s!==''){$sql.=' WHERE handle LIKE ? OR name LIKE ?';$args=['%'.ltrim($s,'@').'%','%'.$s.'%'];}$sql.=' ORDER BY created DESC LIMIT 100';return array_values(array_map(fn($p)=>$this->view($p,$who),array_filter($this->q($sql,$args)->fetchAll(),fn($p)=>$p['user_id']===$who||!$this->blocked($who,$p['user_id']))));}
        if($path==='/connections'&&$method==='GET')return array_values(array_map(fn($p)=>$this->view($p,$who),array_filter($this->q('SELECT * FROM community_profiles WHERE user_id<>? ORDER BY created DESC LIMIT 200',[$who])->fetchAll(),fn($p)=>!$this->blocked($who,$p['user_id']))));
        if($path==='/blocks'&&$method==='GET')return $this->q('SELECT p.user_id id,p.handle FROM community_blocks b JOIN community_profiles p ON p.user_id=b.blocked_id WHERE b.user_id=?',[$who])->fetchAll();
        if($path==='/ranking'&&$method==='GET')return $this->board($who,(string)($_GET['scope']??'friends'),max(0,(int)($_GET['offset']??0)),$mine);
        if($path==='/gyms'&&$method==='GET'){ $q=$this->gymKey($this->txt((string)($_GET['q']??''),120));$city=$this->gymKey($this->txt((string)($_GET['city']??''),120));$rows=$this->q("SELECT id,'manual' provider,name,'' address,city,'active' status FROM community_gyms ORDER BY name LIMIT 200")->fetchAll();return array_values(array_filter($rows,fn($g)=>($q===''||str_contains($this->gymKey($g['name']),$q))&&($city===''||$this->gymKey($g['city'])===$city)));}
        if($path==='/gyms'&&$method==='POST'){$name=$this->txt($data['name']??'',120,true);$city=$this->txt($data['city']??'',120);$nameKey=$this->gymKey($name);$cityKey=$this->gymKey($city);$g=null;foreach($this->q('SELECT * FROM community_gyms ORDER BY created ASC LIMIT 500')->fetchAll() as $candidate){if($this->gymKey($candidate['name'])===$nameKey&&$this->gymKey($candidate['city'])===$cityKey){$g=$candidate;break;}}if(!$g){$g=['id'=>$this->id(),'name'=>$name,'city'=>$city];$this->q('INSERT INTO community_gyms(id,name,city,created)VALUES(?,?,?,?)',[$g['id'],$name,$city,time()]);}return['id'=>$g['id'],'provider'=>'manual','name'=>$g['name'],'address'=>'','city'=>$g['city'],'status'=>'active'];}
        if($path==='/posts'&&$method==='POST'){$caption=$this->txt($data['caption']??'',500,true);$id=$this->id();$this->q('INSERT INTO community_posts(id,user_id,caption,created)VALUES(?,?,?,?)',[$id,$who,$caption,time()]);return['id'=>$id];}
        if($path==='/posts'&&$method==='GET'){$following=(string)($_GET['following']??'')==='1';$owner=(string)($_GET['user']??'');$offset=max(0,(int)($_GET['offset']??0));$sql='SELECT p.*,u.handle,u.name,(SELECT COUNT(*) FROM community_post_likes l WHERE l.post_id=p.id) likes FROM community_posts p JOIN community_profiles u ON u.user_id=p.user_id';$args=[];$where=[];if($owner!==''){$where[]='p.user_id=?';$args[]=$owner;}if($following){$where[]='EXISTS(SELECT 1 FROM community_follows f WHERE f.follower_id=? AND f.followed_id=p.user_id)';$args[]=$who;}if($where)$sql.=' WHERE '.implode(' AND ',$where);$sql.=' ORDER BY p.created DESC LIMIT 21 OFFSET '.$offset;$rows=array_values(array_filter($this->q($sql,$args)->fetchAll(),fn($r)=>!$this->blocked($who,$r['user_id'])));$more=count($rows)>20;if($more)array_pop($rows);return['posts'=>array_map(fn($r)=>$this->post($r,$who),$rows),'next'=>$more?$offset+20:null];}
        if(preg_match('#^/posts/([a-f0-9]{32})/like$#i',$path,$m)&&in_array($method,['PUT','DELETE'],true)){if($method==='PUT')$this->q('INSERT IGNORE INTO community_post_likes(post_id,user_id,created)VALUES(?,?,?)',[$m[1],$who,time()]);else$this->q('DELETE FROM community_post_likes WHERE post_id=? AND user_id=?',[$m[1],$who]);return['ok'=>true];}
        if(preg_match('#^/posts/([a-f0-9]{32})$#i',$path,$m)&&$method==='DELETE'){$this->q('DELETE FROM community_posts WHERE id=? AND user_id=?',[$m[1],$who]);return['ok'=>true];}
        if(preg_match('#^/follow/([a-f0-9]{32})$#i',$path,$m)&&in_array($method,['PUT','DELETE'],true)){$target=$m[1];if($target===$who||!$this->q('SELECT 1 FROM community_profiles WHERE user_id=?',[$target])->fetch()||$this->blocked($who,$target))$this->bad(400,'No se puede seguir a esta persona.');if($method==='PUT'){$follow=$this->q('INSERT IGNORE INTO community_follows(follower_id,followed_id,created)VALUES(?,?,?)',[$who,$target,time()]);if($follow->rowCount())$this->q('INSERT IGNORE INTO community_notifications(id,recipient_id,actor_id,type,created)VALUES(?,?,?,?,?)',[$this->id(),$target,$who,'follow',time()]);}else$this->q('DELETE FROM community_follows WHERE follower_id=? AND followed_id=?',[$who,$target]);return$this->view($this->profile($target,''),$who);}
        if($path==='/notifications'&&$method==='GET'){return $this->q('SELECT n.id,n.type,n.created,n.read_at,p.user_id actorId,p.handle,p.name,p.avatar FROM community_notifications n JOIN community_profiles p ON p.user_id=n.actor_id WHERE n.recipient_id=? ORDER BY n.created DESC LIMIT 30',[$who])->fetchAll();}
        if($path==='/notifications/read'&&$method==='PATCH'){$this->q('UPDATE community_notifications SET read_at=? WHERE recipient_id=? AND read_at IS NULL',[time(),$who]);return['ok'=>true];}
        if(preg_match('#^/blocks/([a-f0-9]{32})$#i',$path,$m)&&in_array($method,['PUT','DELETE'],true)){$target=$m[1];if($target===$who)$this->bad(400,'No puedes bloquearte.');if($method==='PUT'){$this->q('INSERT IGNORE INTO community_blocks(user_id,blocked_id,created)VALUES(?,?,?)',[$who,$target,time()]);$this->q('DELETE FROM community_follows WHERE (follower_id=? AND followed_id=?) OR (follower_id=? AND followed_id=?)',[$who,$target,$target,$who]);}else$this->q('DELETE FROM community_blocks WHERE user_id=? AND blocked_id=?',[$who,$target]);return['ok'=>true];}
        if(in_array($path,['/reports','/profile-reports'],true)&&$method==='POST'){$target=$this->txt($data[$path==='/reports'?'postId':'userId']??'',64,true);$reason=$this->txt($data['reason']??'',500,true);$this->q('INSERT INTO community_reports(id,reporter_id,target_type,target_id,reason,created)VALUES(?,?,?,?,?,?)',[$this->id(),$who,$path==='/reports'?'post':'profile',$target,$reason,time()]);return['ok'=>true];}
        if($path==='/coaching'&&$method==='GET'){$rows=$this->q('SELECT c.*,p.user_id,p.handle,p.name,p.avatar FROM community_coaching c JOIN community_profiles p ON p.user_id=IF(c.client_id=?,c.trainer_id,c.client_id) WHERE c.client_id=? OR c.trainer_id=? ORDER BY c.updated DESC',[$who,$who,$who])->fetchAll();return array_map(fn($r)=>['id'=>$r['id'],'status'=>$r['status'],'role'=>$r['trainer_id']===$who?'trainer':'client','requestedByMe'=>$r['trainer_id']===$who,'created'=>gmdate('c',$r['created']),'updated'=>gmdate('c',$r['updated']),'person'=>['id'=>$r['user_id'],'handle'=>$r['handle'],'name'=>$r['name'],'avatar'=>$r['avatar']]],$rows);}
        if($path==='/coaching/requests'&&$method==='POST'){$client=$this->txt($data['targetId']??'',64,true);if($client===$who||!$this->q('SELECT 1 FROM community_profiles WHERE user_id=?',[$client])->fetch())$this->bad(400,'No se puede solicitar colaboración.');$now=time();$this->q("INSERT INTO community_coaching(id,client_id,trainer_id,status,created,updated)VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE status='pending',updated=VALUES(updated)",[$this->id(),$client,$who,'pending',$now,$now]);return['ok'=>true];}
        if(preg_match('#^/coaching/([a-f0-9]{32})$#i',$path,$m)&&$method==='PATCH'){$r=$this->coach($m[1],$who);$a=$data['action']??'';if($a==='accept'&&$r['client_id']===$who)$this->q("UPDATE community_coaching SET status='active',updated=? WHERE id=?",[time(),$m[1]]);elseif(in_array($a,['decline','revoke'],true))$this->q('DELETE FROM community_coaching WHERE id=?',[$m[1]]);else$this->bad(400,'Acción de colaboración no válida.');return['ok'=>true];}
        if($path==='/coaching/routine/me'&&$method==='PUT'){$r=$this->q("SELECT * FROM community_coaching WHERE client_id=? AND status='active' LIMIT 1",[$who])->fetch();if(!$r)$this->bad(403,'No tienes una colaboración activa.');$this->q('INSERT INTO community_coaching_routines(coaching_id,payload,revision,updated,author_id)VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE payload=VALUES(payload),revision=revision+1,updated=VALUES(updated),author_id=VALUES(author_id)',[$r['id'],json_encode($data,JSON_UNESCAPED_UNICODE),1,time(),$who]);return['ok'=>true];}
        if(preg_match('#^/coaching/([a-f0-9]{32})/routine$#i',$path,$m)&&in_array($method,['GET','PUT'],true)){$r=$this->coach($m[1],$who);if($method==='PUT'){if($r['trainer_id']!==$who)$this->bad(403,'Solo el entrenador puede modificar esta rutina.');$this->q('INSERT INTO community_coaching_routines(coaching_id,payload,revision,updated,author_id)VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE payload=VALUES(payload),revision=revision+1,updated=VALUES(updated),author_id=VALUES(author_id)',[$m[1],json_encode($data,JSON_UNESCAPED_UNICODE),1,time(),$who]);}$managed=$this->q('SELECT * FROM community_coaching_routines WHERE coaching_id=?',[$m[1]])->fetch();if(!$managed)$this->bad(404,'La rutina aún no está disponible.');$author=$this->profile($managed['author_id'],'');return['routine'=>json_decode($managed['payload'],true),'revision'=>(int)$managed['revision'],'updated'=>gmdate('c',$managed['updated']),'author'=>['id'=>$author['user_id'],'handle'=>$author['handle'],'name'=>$author['name']]];}
        if(preg_match('#^/profiles/([a-f0-9]{32})/(followers|following)$#i',$path,$m)&&$method==='GET'){$sql=$m[2]==='followers'?'SELECT p.* FROM community_follows f JOIN community_profiles p ON p.user_id=f.follower_id WHERE f.followed_id=?':'SELECT p.* FROM community_follows f JOIN community_profiles p ON p.user_id=f.followed_id WHERE f.follower_id=?';return array_values(array_map(fn($p)=>$this->view($p,$who),array_filter($this->q($sql,[$m[1]])->fetchAll(),fn($p)=>!$this->blocked($who,$p['user_id']))));}
        if(preg_match('#^/profiles/([a-f0-9]{32})/progress$#i',$path,$m)&&$method==='GET'){$p=$this->profile($m[1],'');if(!($m[1]===$who||$p['progress_visibility']==='public'||($p['progress_visibility']==='friends'&&$this->connected($who,$m[1]))))$this->bad(403,'Este progreso es privado o solo está disponible entre seguidores mutuos.');$r=$this->q('SELECT payload FROM community_progress WHERE user_id=?',[$m[1]])->fetch();if(!$r)$this->bad(404,'Progreso no disponible.');return json_decode($r['payload'],true);}
        if(preg_match('#^/routines/([a-f0-9]{32})$#i',$path,$m)&&$method==='GET'){$p=$this->profile($m[1],'');if(!($m[1]===$who||(bool)$p['routine_public']||$this->connected($who,$m[1])))$this->bad(403,'Esta rutina es privada o solo está disponible entre seguidores mutuos.');$r=$this->q('SELECT payload,updated FROM community_routines WHERE user_id=?',[$m[1]])->fetch();if(!$r)$this->bad(404,'Rutina no disponible.');return['id'=>$m[1],'owner'=>['handle'=>$p['handle'],'name'=>$p['name']],'routine'=>json_decode($r['payload'],true),'updated'=>$r['updated']];}
        if(preg_match('#^/profiles/([a-f0-9]{32})$#i',$path,$m)&&$method==='GET'){if($this->blocked($who,$m[1]))$this->bad(404,'Perfil no encontrado.');return$this->view($this->profile($m[1],''),$who);}
        $this->bad(404,'Ruta de Comunidad no disponible.');
    }
}
