<?php
declare(strict_types=1);
namespace Akhyles;

/** First-party Community data. Account identity is the only authentication. */
final class Community {
    public function __construct(private \PDO $db) { $db->setAttribute(\PDO::ATTR_ERRMODE,\PDO::ERRMODE_EXCEPTION);$db->setAttribute(\PDO::ATTR_DEFAULT_FETCH_MODE,\PDO::FETCH_ASSOC);$this->migrate();$this->migrateTrainerWorkspace(); }
    private function migrate(): void { foreach([
        'CREATE TABLE IF NOT EXISTS community_follows (follower_id VARCHAR(64) NOT NULL,followed_id VARCHAR(64) NOT NULL,created BIGINT NOT NULL,PRIMARY KEY(follower_id,followed_id),INDEX(followed_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS community_notifications (id CHAR(32) PRIMARY KEY,recipient_id VARCHAR(64) NOT NULL,actor_id VARCHAR(64) NOT NULL,type VARCHAR(32) NOT NULL,created BIGINT NOT NULL,read_at BIGINT NULL,UNIQUE KEY notification_once(recipient_id,actor_id,type),INDEX notification_recipient(recipient_id,read_at,created)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS community_blocks (user_id VARCHAR(64) NOT NULL,blocked_id VARCHAR(64) NOT NULL,created BIGINT NOT NULL,PRIMARY KEY(user_id,blocked_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS community_posts (id CHAR(32) PRIMARY KEY,user_id VARCHAR(64) NOT NULL,caption VARCHAR(500) NOT NULL,created BIGINT NOT NULL,INDEX(created),INDEX(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS community_post_likes (post_id CHAR(32) NOT NULL,user_id VARCHAR(64) NOT NULL,created BIGINT NOT NULL,PRIMARY KEY(post_id,user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS community_reports (id CHAR(32) PRIMARY KEY,reporter_id VARCHAR(64) NOT NULL,target_type VARCHAR(16) NOT NULL,target_id VARCHAR(64) NOT NULL,reason VARCHAR(500) NOT NULL,created BIGINT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS community_gyms (id CHAR(32) PRIMARY KEY,name VARCHAR(120) NOT NULL,city VARCHAR(120) NOT NULL DEFAULT \'\',created BIGINT NOT NULL,UNIQUE KEY gym_name_city(name,city)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS community_coaching (id CHAR(32) PRIMARY KEY,client_id VARCHAR(64) NOT NULL,trainer_id VARCHAR(64) NOT NULL,status VARCHAR(16) NOT NULL,created BIGINT NOT NULL,updated BIGINT NOT NULL,UNIQUE KEY coaching_pair(client_id,trainer_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS community_coaching_routines (coaching_id CHAR(32) PRIMARY KEY,payload MEDIUMTEXT NOT NULL,revision INT NOT NULL DEFAULT 1,updated BIGINT NOT NULL,author_id VARCHAR(64) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS community_achievements (id CHAR(32) PRIMARY KEY,user_id VARCHAR(64) NOT NULL,type VARCHAR(32) NOT NULL,kind VARCHAR(32) NOT NULL,definition_id VARCHAR(160) NULL,tier_id VARCHAR(32) NULL,exercise_id VARCHAR(80) NULL,exercise_name VARCHAR(160) NULL,details MEDIUMTEXT NOT NULL,created BIGINT NOT NULL,dedupe_key VARCHAR(160) NULL,INDEX achievement_user(user_id,created),INDEX achievement_definition(definition_id),UNIQUE KEY achievement_dedupe(user_id,dedupe_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS community_achievement_likes (achievement_id CHAR(32) NOT NULL,user_id VARCHAR(64) NOT NULL,created BIGINT NOT NULL,PRIMARY KEY(achievement_id,user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS community_notification_preferences (user_id VARCHAR(64) PRIMARY KEY,achievement_likes TINYINT NOT NULL DEFAULT 1) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        'CREATE TABLE IF NOT EXISTS community_achievement_rarities (definition_id VARCHAR(160) PRIMARY KEY,tier VARCHAR(16) NOT NULL,holders INT NOT NULL,eligible INT NOT NULL,percentage DECIMAL(7,2) NULL,calculated_at BIGINT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
        "CREATE TABLE IF NOT EXISTS community_machine_brands (gym_id CHAR(32) NOT NULL DEFAULT '',exercise_id VARCHAR(80) NOT NULL,brand VARCHAR(60) NOT NULL,uses INT NOT NULL DEFAULT 1,updated BIGINT NOT NULL,PRIMARY KEY(gym_id,exercise_id,brand)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"
    ] as $sql)$this->db->exec($sql);$this->db->exec('CREATE TABLE IF NOT EXISTS community_machine_brands (gym_id CHAR(32) NULL,exercise_id VARCHAR(80) NOT NULL,brand VARCHAR(60) NOT NULL,uses INT NOT NULL DEFAULT 1,updated BIGINT NOT NULL,PRIMARY KEY(gym_id,exercise_id,brand)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');$this->db->exec('CREATE TABLE IF NOT EXISTS community_exercise_proposals (id CHAR(32) PRIMARY KEY,user_id VARCHAR(64) NOT NULL,name VARCHAR(120) NOT NULL,payload MEDIUMTEXT NOT NULL,status VARCHAR(16) NOT NULL DEFAULT \'pending\',created BIGINT NOT NULL,INDEX(status,created)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');$this->db->exec('CREATE TABLE IF NOT EXISTS community_trainer_profiles (user_id VARCHAR(64) PRIMARY KEY,public TINYINT NOT NULL DEFAULT 0,specialties MEDIUMTEXT NOT NULL,modalities MEDIUMTEXT NOT NULL,experience_years INT NOT NULL DEFAULT 0,credentials VARCHAR(500) NOT NULL DEFAULT \'\',availability VARCHAR(160) NOT NULL DEFAULT \'\',pricing VARCHAR(160) NOT NULL DEFAULT \'\',stats_public TINYINT NOT NULL DEFAULT 0,updated BIGINT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');foreach(['trainer_enabled TINYINT NOT NULL DEFAULT 0','achievements_public TINYINT NOT NULL DEFAULT 0',"achievements_visibility VARCHAR(16) NOT NULL DEFAULT 'private'","gym_id CHAR(32) NULL"] as $column)try{$this->db->exec('ALTER TABLE community_profiles ADD COLUMN '.$column);}catch(\PDOException){} $this->db->exec("UPDATE community_profiles SET achievements_visibility='public' WHERE achievements_public=1 AND achievements_visibility='private'");foreach(['definition_id VARCHAR(160) NULL','INDEX achievement_definition(definition_id)'] as $change)try{$this->db->exec('ALTER TABLE community_achievements ADD '.$change);}catch(\PDOException){} }
    /** Additive migration for the private trainer-workspace experiment. */
    private function migrateTrainerWorkspace(): void {
        foreach([
            'CREATE TABLE IF NOT EXISTS community_coaching_notes (id CHAR(32) PRIMARY KEY,coaching_id CHAR(32) NOT NULL,author_id VARCHAR(64) NOT NULL,body VARCHAR(1200) NOT NULL,created BIGINT NOT NULL,updated BIGINT NOT NULL,archived TINYINT NOT NULL DEFAULT 0,INDEX(coaching_id,updated)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
            'CREATE TABLE IF NOT EXISTS community_coaching_snapshots (coaching_id CHAR(32) NOT NULL,week_start DATE NOT NULL,adherence DECIMAL(5,2) NULL,strength_percent DECIMAL(8,2) NULL,sessions_completed INT NOT NULL DEFAULT 0,sessions_scheduled INT NOT NULL DEFAULT 0,eligible TINYINT NOT NULL DEFAULT 0,level VARCHAR(24) NOT NULL DEFAULT \'\',updated BIGINT NOT NULL,PRIMARY KEY(coaching_id,week_start),INDEX(week_start)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4'
        ] as $sql) $this->db->exec($sql);
        foreach(['requested_by VARCHAR(64) NULL','accepted BIGINT NULL','ended BIGINT NULL','revoked_by VARCHAR(64) NULL'] as $column) try { $this->db->exec('ALTER TABLE community_coaching ADD COLUMN '.$column); } catch(\PDOException) {}
        $this->db->exec("UPDATE community_coaching SET requested_by=trainer_id WHERE requested_by IS NULL OR requested_by='' ");
        $this->db->exec("UPDATE community_coaching SET accepted=updated WHERE status='active' AND accepted IS NULL");
    }
    private function trainerPermissions(string $coachingId): array {
        // An active coaching relationship is an all-access sports relationship.
        // Legacy permission rows remain in storage only to avoid destructive migrations.
        return ['routine'=>true,'progress'=>true,'aggregate'=>true];
    }
    private function trainerClient(array $row): array {
        $permissions=$this->trainerPermissions($row['id']);$progress=null;
        if($permissions['progress']) { $stored=$this->q('SELECT payload,updated FROM community_coaching_progress WHERE client_id=? AND trainer_id=?',[$row['client_id'],$row['trainer_id']])->fetch(); if($stored) $progress=json_decode($stored['payload'],true); }
        $weekly=is_array($progress['weekly']??null)?$progress['weekly']:[];
        $routine=$this->q('SELECT revision,author_id,updated FROM community_coaching_routines WHERE coaching_id=?',[$row['id']])->fetch();
        $status=$routine ? (($routine['author_id']===$row['trainer_id'])?'sent':'applied') : 'none';
        $last=is_array($progress)?($progress['updated']??null):null;
        $adherence=is_numeric($weekly['adherence']??null)?round((float)$weekly['adherence'],1):null;
        $strength=is_numeric($weekly['strengthPercent']??null)?round((float)$weekly['strengthPercent'],1):null;
        $attention=$status==='sent'?'routine-pending':($adherence!==null&&$adherence<55?'needs-review':($last&&strtotime((string)$last)<time()-604800?'inactive':'on-track'));
        return ['relationshipId'=>$row['id'],'id'=>$row['user_id'],'name'=>$row['name'],'handle'=>$row['handle'],'avatar'=>$row['avatar'],'level'=>$row['level'],'activeSince'=>$row['accepted']?gmdate('c',(int)$row['accepted']):null,'lastActivity'=>$last,'scheduled'=>(int)($weekly['scheduled']??0),'completed'=>(int)($weekly['completed']??0),'adherence'=>$adherence,'strengthPercent'=>$strength,'points'=>is_numeric($progress['points']??null)?(float)$progress['points']:null,'progress'=>$progress,'routineStatus'=>$status,'attention'=>$attention];
    }
    private function trainerRows(string $who,string $status='active'): array { return $this->q('SELECT c.*,p.user_id,p.handle,p.name,p.avatar,p.level FROM community_coaching c JOIN community_profiles p ON p.user_id=c.client_id WHERE c.trainer_id=? AND c.status=? ORDER BY c.updated DESC',[$who,$status])->fetchAll(); }
    private function trainerPublicStats(string $trainerId): array {
        $rows=$this->trainerRows($trainerId);$clients=array_map(fn($row)=>$this->trainerClient($row),$rows);$eligible=array_values(array_filter($clients,fn($client)=>$client['adherence']!==null&&$client['strengthPercent']!==null));
        $mid=function(array $values):?float{sort($values);$count=count($values);if(!$count)return null;$middle=intdiv($count,2);return round($count%2?$values[$middle]:($values[$middle-1]+$values[$middle])/2,1);};
        $adherence=$mid(array_column($eligible,'adherence'));$strength=$mid(array_column($eligible,'strengthPercent'));$constant=$eligible?round(count(array_filter($eligible,fn($client)=>$client['adherence']>=75))*100/count($eligible),1):null;
        return ['clientsActive'=>count($clients),'eligibleClients'=>count($eligible),'sampleSufficient'=>count($eligible)>=5,'adherenceMedian'=>$adherence,'strengthMedian'=>$strength,'consistencyRate'=>$constant,'periodDays'=>84,'calculatedAt'=>gmdate('c'),'methodology'=>'Medianas de 12 semanas de colaboraciones activas con datos comparables.'];
    }
    private function q(string $sql,array $v=[]): \PDOStatement{$s=$this->db->prepare($sql);$s->execute($v);return $s;}
    private function bad(int $code,string $text):never{throw new ApiError($code,$text);} private function id():string{return bin2hex(random_bytes(16));}
    private function txt(mixed $v,int $max,bool $required=false):string{if(!is_string($v)||mb_strlen($v,'UTF-8')>$max)$this->bad(400,'Revisa los campos indicados.');$v=trim($v);if($required&&$v==='')$this->bad(400,'Revisa los campos indicados.');return $v;}
    private function avatar(mixed $value):string{$value=$this->txt($value,2000000);if(in_array($value,['mountain','sun','wave','star','bolt','moon'],true))return$value;if(!preg_match('#^data:image/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$#',$value))$this->bad(400,'La imagen de perfil no es válida.');return$value;}
    /** Stable comparison key: casing, accents, punctuation and repeated spaces never create another gym. */
    private function gymKey(string $value):string{$value=trim(mb_strtolower($value,'UTF-8'));$plain=iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$value);if($plain!==false)$value=$plain;$value=preg_replace('/[^a-z0-9]+/',' ',$value)??'';return trim(preg_replace('/\s+/',' ',$value)??'');}
    private function yes(mixed $v):bool{if(!is_bool($v))$this->bad(400,'Revisa las opciones de privacidad.');return $v;}
    private function profile(string $id,string $name):array{$p=$this->q('SELECT * FROM community_profiles WHERE user_id=?',[$id])->fetch();if($p)return $p;$handle='akh_'.substr($id,0,16);$this->q("INSERT INTO community_profiles(user_id,handle,name,avatar,created)VALUES(?,?,?,?,?)",[$id,$handle,mb_strcut($name?:'Atleta',0,80,'UTF-8'),'mountain',time()]);return $this->q('SELECT * FROM community_profiles WHERE user_id=?',[$id])->fetch();}
    private function existing(string $id):array{$p=$this->q('SELECT * FROM community_profiles WHERE user_id=?',[$id])->fetch();if(!$p)$this->bad(404,'Perfil no encontrado.');return $p;}
    private function following(string $a,string $b):bool{return(bool)$this->q('SELECT 1 FROM community_follows WHERE follower_id=? AND followed_id=?',[$a,$b])->fetchColumn();}
    private function connected(string $a,string $b):bool{return $this->following($a,$b)&&$this->following($b,$a);}
    private function blocked(string $a,string $b):bool{return(bool)$this->q('SELECT 1 FROM community_blocks WHERE (user_id=? AND blocked_id=?) OR (user_id=? AND blocked_id=?)',[$a,$b,$b,$a])->fetchColumn();}
    private function view(array $p,string $who):array{$id=$p['user_id'];$self=$id===$who;$following=$self?false:$this->following($who,$id);$followsYou=$self?false:$this->following($id,$who);$friends=$self||($following&&$followsYou);$routine=(bool)$this->q('SELECT 1 FROM community_routines WHERE user_id=?',[$id])->fetchColumn();$progress=(bool)$this->q('SELECT 1 FROM community_progress WHERE user_id=?',[$id])->fetchColumn();$visibility=$p['progress_visibility'];$achievementVisibility=$p['achievements_visibility']??((bool)($p['achievements_public']??false)?'public':'private');$visible=$self||$visibility==='public'||($visibility==='friends'&&$friends);return ['id'=>$id,'handle'=>$p['handle'],'name'=>$p['name'],'bio'=>$p['bio'],'avatar'=>$p['avatar'],'level'=>$p['level'],'posts'=>(int)$this->q('SELECT COUNT(*) FROM community_achievements WHERE user_id=?',[$id])->fetchColumn(),'followers'=>(int)$this->q('SELECT COUNT(*) FROM community_follows WHERE followed_id=?',[$id])->fetchColumn(),'following'=>(int)$this->q('SELECT COUNT(*) FROM community_follows WHERE follower_id=?',[$id])->fetchColumn(),'followed'=>$following,'followsYou'=>$followsYou,'connected'=>$friends,'trainerEnabled'=>(bool)($p['trainer_enabled']??false),'routineId'=>$routine&&$visible?$id:null,'progressVisible'=>$progress&&$visible,'trainingPlace'=>$p['training_place'],'gymId'=>$p['gym_id']??null,'city'=>$p['city'],'routinePublic'=>(bool)$p['routine_public'],'progressPublic'=>$visibility!=='private','progressVisibility'=>$visibility,'trainingVisibility'=>$visibility,'detailsPublic'=>(bool)$p['details_public'],'bodyWeightPublic'=>(bool)$p['body_weight_public'],'rankingPublic'=>(bool)$p['ranking_public'],'achievementsPublic'=>$achievementVisibility!=='private','achievementsVisibility'=>$achievementVisibility];}
    private function post(array $r,string $who):array{return['id'=>$r['id'],'userId'=>$r['user_id'],'handle'=>$r['handle'],'name'=>$r['name'],'caption'=>$r['caption'],'created'=>gmdate('c',(int)$r['created']),'likes'=>(int)$r['likes'],'liked'=>(bool)$this->q('SELECT 1 FROM community_post_likes WHERE post_id=? AND user_id=?',[$r['id'],$who])->fetchColumn()];}
    private function initialRarity(string $definition):string{if(preg_match('/local:sessions-(\d+)/',$definition,$m))return(int)$m[1]>=500?'legendary':((int)$m[1]>=250?'epic':((int)$m[1]>=100?'rare':((int)$m[1]>=25?'uncommon':'common')));if(preg_match('/local:prs-(\d+)/',$definition,$m))return(int)$m[1]>=50?'epic':((int)$m[1]>=25?'rare':'uncommon');if(preg_match('/(?:tier:|points-)(\d+)/',$definition,$m))return(int)$m[1]>=900?'legendary':((int)$m[1]>=600?'epic':((int)$m[1]>=400?'rare':((int)$m[1]>=200?'uncommon':'common')));if(str_starts_with($definition,'local:return-')||str_starts_with($definition,'pr:'))return'uncommon';return'common';}
    private function rarity(string $definition):array{$now=time();$cached=$this->q('SELECT * FROM community_achievement_rarities WHERE definition_id=?',[$definition])->fetch();if($cached&&$cached['tier']!=='provisional'&&$now-(int)$cached['calculated_at']<86400)return['tier'=>$cached['tier'],'holders'=>(int)$cached['holders'],'eligible'=>(int)$cached['eligible'],'percentage'=>$cached['percentage']===null?null:(float)$cached['percentage'],'calculatedAt'=>gmdate('c',(int)$cached['calculated_at'])];$holders=(int)$this->q('SELECT COUNT(DISTINCT user_id) FROM community_achievements WHERE definition_id=? OR (definition_id IS NULL AND dedupe_key=?)',[$definition,$definition])->fetchColumn();$eligible=(int)$this->q('SELECT COUNT(DISTINCT user_id) FROM community_achievements')->fetchColumn();$percentage=$eligible>=100?round($holders*100/$eligible,2):null;$tier=$percentage===null?$this->initialRarity($definition):($percentage<1?'legendary':($percentage<5?'epic':($percentage<20?'rare':($percentage<=50?'uncommon':'common'))));$this->q('INSERT INTO community_achievement_rarities(definition_id,tier,holders,eligible,percentage,calculated_at)VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE tier=VALUES(tier),holders=VALUES(holders),eligible=VALUES(eligible),percentage=VALUES(percentage),calculated_at=VALUES(calculated_at)',[$definition,$tier,$holders,$eligible,$percentage,$now]);return['tier'=>$tier,'holders'=>$holders,'eligible'=>$eligible,'percentage'=>$percentage,'calculatedAt'=>gmdate('c',$now)];}
    private function achievement(array $r,string $who):array{$d=json_decode((string)$r['details'],true);$definition=(string)($r['definition_id']??$r['dedupe_key']??$r['id']);return['id'=>$r['id'],'userId'=>$r['user_id'],'handle'=>$r['handle'],'name'=>$r['name'],'type'=>$r['type'],'kind'=>$r['kind'],'tierId'=>$r['tier_id'],'exerciseId'=>$r['exercise_id'],'exerciseName'=>$r['exercise_name'],'definitionId'=>$definition,'details'=>is_array($d)?$d:[],'created'=>gmdate('c',(int)$r['created']),'likes'=>(int)$r['likes'],'liked'=>(bool)$r['liked'],'rarity'=>$this->rarity($definition)];}
    private function canAchievements(string $owner,string $who):bool{$p=$this->existing($owner);$visibility=$p['achievements_visibility']??((bool)($p['achievements_public']??false)?'public':'private');return $owner===$who||($visibility==='public'||($visibility==='friends'&&$this->connected($who,$owner)))&&!$this->blocked($who,$owner);}
    private function recordAchievements(string $who,array $before,array $current):void{$old=(float)($before['points']??0);$now=(float)($current['points']??0);foreach([100,200,300,400,500,600,700,800,900,1000] as $minimum)if($old<$minimum&&$now>=$minimum)$this->q('INSERT IGNORE INTO community_achievements(id,user_id,type,kind,tier_id,details,created,dedupe_key)VALUES(?,?,?,?,?,?,?,?)',[$this->id(),$who,'tier','tier','points-'.$minimum,json_encode(['beforePoints'=>$old,'afterPoints'=>$now],JSON_UNESCAPED_UNICODE),time(),'tier:'.$minimum]);$previous=[];foreach(($before['exercises']??[]) as $e)if(is_array($e)&&isset($e['id']))$previous[$e['id']]=$e;foreach(($current['exercises']??[]) as $e){if(!is_array($e)||!isset($e['id']))continue;$oldMax=(float)($previous[$e['id']]['maximum']??0);$max=(float)($e['maximum']??0);if($oldMax>0&&$max>$oldMax+0.05)$this->q('INSERT IGNORE INTO community_achievements(id,user_id,type,kind,exercise_id,exercise_name,details,created,dedupe_key)VALUES(?,?,?,?,?,?,?,?,?)',[$this->id(),$who,'personal_best','personal_best',(string)$e['id'],mb_substr((string)($e['name']??'Ejercicio'),0,160),json_encode(['beforeMaximum'=>$oldMax,'maximum'=>$max,'weight'=>$e['weight']??null,'reps'=>$e['reps']??null,'date'=>$e['date']??null],JSON_UNESCAPED_UNICODE),time(),'pr:'.$e['id'].':'.($e['date']??time())]);}}
    private function coach(string $id,string $who):array{$r=$this->q('SELECT * FROM community_coaching WHERE id=? AND (client_id=? OR trainer_id=?)',[$id,$who,$who])->fetch();if(!$r)$this->bad(404,'Colaboración no disponible.');return $r;}
    private function ranked(array $rows):array{usort($rows,fn($a,$b)=>$b['points']<=>$a['points']?:strcmp($a['handle'],$b['handle']));$rank=0;foreach($rows as $i=>&$row){if($i===0||$row['points']!==$rows[$i-1]['points'])$rank=$i+1;$row['rank']=$rank;}unset($row);return $rows;}
    private function board(string $who,string $scope,int $offset,array $me,string $requestedCity=''):array{if(!in_array($scope,['friends','global','gym','city'],true))$this->bad(400,'Clasificación no válida.');$location=$scope==='gym'?$me['training_place']:($scope==='city'?(trim($requestedCity)?:$me['city']):'');if(in_array($scope,['gym','city'],true)&&!$location)return['entries'=>[],'next'=>null,'total'=>0,'me'=>null,'nextRival'=>null,'gap'=>null,'needsLocation'=>true,'location'=>''];$all=[];$candidate=null;foreach($this->q('SELECT p.*,g.payload FROM community_profiles p JOIN community_progress g ON g.user_id=p.user_id WHERE p.ranking_public=1')->fetchAll() as $p){if($this->blocked($who,$p['user_id']))continue;$d=json_decode($p['payload'],true);if(!is_array($d)||empty($d['pointsRankingEligible'])||!is_numeric($d['points']??null))continue;$entry=['id'=>$p['user_id'],'handle'=>$p['handle'],'name'=>$p['name'],'avatar'=>$p['avatar'],'points'=>(float)$d['points'],'coverage'=>(int)($d['pointsCoverage']??0),'reliability'=>(int)($d['pointsReliability']??0)];if($p['user_id']===$who)$candidate=$entry;if($scope==='friends'&&$p['user_id']!==$who&&!$this->connected($who,$p['user_id']))continue;if($scope==='gym'&&(($me['gym_id']??'')!==''?($p['gym_id']??'')!==$me['gym_id']:$this->gymKey($p['training_place'])!==$this->gymKey($location)))continue;if($scope==='city'&&$this->gymKey($p['city'])!==$this->gymKey($location))continue;$all[]=$entry;}$all=$this->ranked($all);$mine=array_values(array_filter($all,fn($e)=>$e['id']===$who))[0]??null;if(!$mine&&$scope==='city'&&$candidate){$projected=$this->ranked([...$all,$candidate]);$mine=array_values(array_filter($projected,fn($e)=>$e['id']===$who))[0]??null;if($mine)$mine['projected']=true;}$higher=$mine?array_values(array_filter($all,fn($e)=>$e['points']>$mine['points'])):[];$rival=$higher?end($higher):null;return['entries'=>array_slice($all,$offset,20),'next'=>$offset+20<count($all)?$offset+20:null,'total'=>count($all),'me'=>$mine,'nextRival'=>$rival,'gap'=>$mine&&$rival?round($rival['points']-$mine['points'],1):null,'needsLocation'=>false,'location'=>$location];}
    private function syncPersonalAchievements(string $who,array $items):array{if(count($items)>200)$this->bad(400,'Demasiados logros.');$stored=0;foreach($items as $item){if(!is_array($item)||!preg_match('/^[a-z0-9:_-]{1,120}$/i',(string)($item['id']??''))||!is_string($item['title']??null)||mb_strlen($item['title'],'UTF-8')>160||!is_string($item['description']??null)||mb_strlen($item['description'],'UTF-8')>300||!is_string($item['unlockedAt']??null)||strtotime($item['unlockedAt'])===false||!in_array($item['category']??'', ['progress','consistency','strength'],true))$this->bad(400,'Formato de logro no válido.');$definition='local:'.$item['id'];$created=strtotime($item['unlockedAt']);$this->q('INSERT IGNORE INTO community_achievements(id,user_id,type,kind,definition_id,details,created,dedupe_key)VALUES(?,?,?,?,?,?,?,?)',[$this->id(),$who,'personal','personal',$definition,json_encode(['title'=>$item['title'],'description'=>$item['description'],'category'=>$item['category']],JSON_UNESCAPED_UNICODE),$created,$definition]);$stored++;}return['ok'=>true,'stored'=>$stored];}
    public function handle(string $method,string $path,array $data,array $principal):array{
        if($path==='/health'&&$method==='GET')return['service'=>'akhyles-community','ok'=>true,'identity'=>'akhyles-account'];try{$this->db->exec('ALTER TABLE community_profiles MODIFY avatar MEDIUMTEXT NOT NULL');}catch(\PDOException){}$who=$principal['id'];$mine=$this->profile($who,$principal['name']);
        if($path==='/trainer/dashboard'&&$method==='GET'){
            if(!(bool)($mine['trainer_enabled']??false))$this->bad(403,'Activa tu perfil de entrenador para abrir este espacio.');
            $clients=array_map(fn($row)=>$this->trainerClient($row),$this->trainerRows($who));$pending=(int)$this->q("SELECT COUNT(*) FROM community_coaching WHERE trainer_id=? AND status='pending' AND requested_by<>?",[$who,$who])->fetchColumn();$eligible=array_values(array_filter($clients,fn($client)=>is_array($client['progress']??null)));
            $mid=function(array $values):?float{$values=array_values(array_filter($values,fn($value)=>$value!==null));sort($values);$count=count($values);if(!$count)return null;$middle=intdiv($count,2);return round($count%2?$values[$middle]:($values[$middle-1]+$values[$middle])/2,1);};
            return ['activeClients'=>count($clients),'pendingRequests'=>$pending,'routinesPending'=>count(array_filter($clients,fn($client)=>$client['routineStatus']==='sent')),'needsAttention'=>count(array_filter($clients,fn($client)=>$client['attention']!=='on-track')),'medianAdherence'=>$mid(array_column($clients,'adherence')),'medianStrengthChange'=>$mid(array_column($clients,'strengthPercent')),'eligibleClients'=>count($eligible),'sampleSufficient'=>count($eligible)>=5,'clients'=>$clients];
        }
        if($path==='/trainer/requests'&&$method==='GET'){
            if(!(bool)($mine['trainer_enabled']??false))$this->bad(403,'Activa tu perfil de entrenador para gestionar solicitudes.');
            $rows=$this->q("SELECT c.*,p.user_id,p.handle,p.name,p.avatar FROM community_coaching c JOIN community_profiles p ON p.user_id=c.client_id WHERE c.trainer_id=? AND c.status='pending' AND c.requested_by<>? ORDER BY c.updated DESC",[$who,$who])->fetchAll();
            return array_map(fn($row)=>['id'=>$row['id'],'status'=>'pending','role'=>'trainer','requestedByMe'=>false,'created'=>gmdate('c',(int)$row['created']),'updated'=>gmdate('c',(int)$row['updated']),'person'=>['id'=>$row['user_id'],'handle'=>$row['handle'],'name'=>$row['name'],'avatar'=>$row['avatar']]],$rows);
        }
        if($path==='/trainer/requests'&&$method==='POST'){
            $target=$this->txt($data['targetId']??'',64,true);$other=$this->existing($target);if($target===$who||$this->blocked($who,$target))$this->bad(400,'No se puede solicitar colaboración.');$mineTrainer=(bool)($mine['trainer_enabled']??false);$otherTrainer=(bool)($other['trainer_enabled']??false);
            if($otherTrainer&&!$mineTrainer){$trainer=$target;$client=$who;}elseif($mineTrainer){$trainer=$who;$client=$target;}else $this->bad(400,'La colaboración requiere un perfil de entrenador activo.');
            $now=time();$existing=$this->q('SELECT id FROM community_coaching WHERE client_id=? AND trainer_id=?',[$client,$trainer])->fetch();
            if($existing)$this->q("UPDATE community_coaching SET status='pending',requested_by=?,accepted=NULL,ended=NULL,revoked_by=NULL,updated=? WHERE id=?",[$who,$now,$existing['id']]);else $this->q('INSERT INTO community_coaching(id,client_id,trainer_id,status,requested_by,created,updated)VALUES(?,?,?,?,?,?,?)',[$this->id(),$client,$trainer,'pending',$who,$now,$now]);
            return ['ok'=>true];
        }
        if(preg_match('#^/trainer/requests/([a-f0-9]{32})$#i',$path,$m)&&$method==='PATCH'){
            $row=$this->q("SELECT * FROM community_coaching WHERE id=? AND trainer_id=? AND status='pending'",[$m[1],$who])->fetch();if(!$row||$row['requested_by']===$who)$this->bad(404,'Solicitud no disponible.');$action=$data['action']??'';
            if($action==='accept'){$this->q("UPDATE community_coaching SET status='active',accepted=?,updated=? WHERE id=?",[time(),time(),$m[1]]);}elseif($action==='decline')$this->q("UPDATE community_coaching SET status='declined',ended=?,updated=? WHERE id=?",[time(),time(),$m[1]]);else $this->bad(400,'Acción de colaboración no válida.');return['ok'=>true];
        }
        if(preg_match('#^/trainer/clients/([a-f0-9]{32})$#i',$path,$m)&&$method==='GET'){$row=$this->q("SELECT c.*,p.user_id,p.handle,p.name,p.avatar,p.level FROM community_coaching c JOIN community_profiles p ON p.user_id=c.client_id WHERE c.id=? AND c.trainer_id=? AND c.status='active'",[$m[1],$who])->fetch();if(!$row)$this->bad(404,'Deportista no disponible.');return $this->trainerClient($row);}
        if(preg_match('#^/trainer/clients/([a-f0-9]{32})/revoke$#i',$path,$m)&&$method==='POST'){$row=$this->q("SELECT id FROM community_coaching WHERE id=? AND trainer_id=? AND status='active'",[$m[1],$who])->fetch();if(!$row)$this->bad(404,'Colaboración no disponible.');$this->q("UPDATE community_coaching SET status='revoked',ended=?,revoked_by=?,updated=? WHERE id=?",[time(),$who,time(),$m[1]]);return['ok'=>true];}
        if(preg_match('#^/profiles/([a-f0-9]{32})/trainer-stats$#i',$path,$m)&&$method==='GET'){$profile=$this->existing($m[1]);$professional=$this->q('SELECT stats_public FROM community_trainer_profiles WHERE user_id=?',[$m[1]])->fetch();if(!$professional||(int)$professional['stats_public']!==1||!(bool)($profile['trainer_enabled']??false))$this->bad(404,'Resultados del entrenador no disponibles.');return $this->trainerPublicStats($m[1]);}
        if($path==='/me'&&$method==='GET')return $this->view($mine,$who);
        if($path==='/me'&&$method==='PATCH'&&array_key_exists('trainerEnabled',$data))$this->q('UPDATE community_profiles SET trainer_enabled=? WHERE user_id=?',[$this->yes($data['trainerEnabled']),$who]);
        if($path==='/me'&&$method==='PATCH'){ $name=$this->txt($data['name']??$mine['name'],80,true);$handle=strtolower(ltrim($this->txt($data['handle']??$mine['handle'],24,true),'@'));if(!preg_match('/^[a-z0-9_]{3,24}$/',$handle))$this->bad(400,'El @ debe tener 3–24 caracteres: letras, números o _.');$level=$data['level']??$mine['level'];if(!in_array($level,['beginner','intermediate','advanced'],true))$this->bad(400,'Revisa tu nivel.');$place=$this->txt($data['trainingPlace']??$mine['training_place'],120);$city=$this->txt($data['city']??$mine['city'],120);$gymId=null;if(array_key_exists('gymId',$data)){if($data['gymId']!==null&&$data['gymId']!==''){$candidate=$this->q('SELECT id,name,city FROM community_gyms WHERE id=?',[$this->txt($data['gymId'],32,true)])->fetch();if(!$candidate)$this->bad(400,'El gimnasio seleccionado ya no existe.');$gymId=$candidate['id'];$place=$candidate['name'];$city=$candidate['city'];}}elseif($place===$mine['training_place']&&$city===$mine['city'])$gymId=$mine['gym_id']??null;try{$this->q('UPDATE community_profiles SET handle=?,name=?,bio=?,level=?,avatar=?,training_place=?,gym_id=?,city=? WHERE user_id=?',[$handle,$name,$this->txt($data['bio']??$mine['bio'],500),$level,$this->avatar($data['avatar']??$mine['avatar']),$place,$gymId,$city,$who]);}catch(\PDOException){$this->bad(409,'Ese @ ya está registrado.');}return $this->view($this->profile($who,$name),$who);}
        if($path==='/me/privacy'&&$method==='PATCH'){$unified=$data['trainingVisibility']??null;if($unified!==null&&!in_array($unified,['private','friends','public'],true))$this->bad(400,'Revisa quién puede ver tus entrenamientos.');$routine=$unified!==null?$unified!=='private':(array_key_exists('routinePublic',$data)?$this->yes($data['routinePublic']):(bool)$mine['routine_public']);$details=$unified!==null?$unified!=='private':(array_key_exists('detailsPublic',$data)?$this->yes($data['detailsPublic']):(bool)$mine['details_public']);$weight=$unified!==null?$unified!=='private':(array_key_exists('bodyWeightPublic',$data)?$this->yes($data['bodyWeightPublic']):(bool)$mine['body_weight_public']);$ranking=array_key_exists('rankingPublic',$data)?$this->yes($data['rankingPublic']):(bool)$mine['ranking_public'];$visibility=$unified??($data['progressVisibility']??(($data['progressPublic']??null)===false?'private':$mine['progress_visibility']));if(!in_array($visibility,['private','friends','public'],true))$this->bad(400,'Revisa las opciones de privacidad.');$this->q('UPDATE community_profiles SET routine_public=?,progress_visibility=?,details_public=?,body_weight_public=?,ranking_public=? WHERE user_id=?',[$routine,$visibility,$details,$weight,$ranking,$who]);return $this->view($this->profile($who,''),$who);}
        if(in_array($path,['/routines/me','/progress/me'],true)&&in_array($method,['PUT','DELETE'],true)){$table=$path==='/routines/me'?'community_routines':'community_progress';if($method==='DELETE'){$this->q("DELETE FROM $table WHERE user_id=?",[$who]);return['ok'=>true];}$before=[];if($path==='/progress/me'){$old=$this->q('SELECT payload FROM community_progress WHERE user_id=?',[$who])->fetch();$decoded=$old?json_decode($old['payload'],true):[];if(is_array($decoded))$before=$decoded;}$payload=json_encode($data,JSON_UNESCAPED_UNICODE);$this->q("INSERT INTO $table(user_id,payload,updated)VALUES(?,?,?) ON DUPLICATE KEY UPDATE payload=VALUES(payload),updated=VALUES(updated)",[$who,$payload,gmdate('c')]);if($path==='/progress/me')$this->recordAchievements($who,$before,$data);return['ok'=>true];}
        if($path==='/comparison'&&in_array($method,['POST','DELETE'],true)){if($method==='DELETE'){$this->q('DELETE FROM community_samples WHERE user_id=?',[$who]);return['ok'=>true];}$this->q('INSERT INTO community_samples(user_id,payload,updated)VALUES(?,?,?) ON DUPLICATE KEY UPDATE payload=VALUES(payload),updated=VALUES(updated)',[$who,json_encode($data,JSON_UNESCAPED_UNICODE),time()]);$peers=(int)$this->q('SELECT COUNT(*) FROM community_samples WHERE user_id<>?',[$who])->fetchColumn();return['status'=>$peers?'available':'insufficient','peers'=>$peers,'rate'=>null,'exercises'=>0];}
        if($path==='/profiles'&&$method==='GET'){$s=trim((string)($_GET['q']??''));$sql='SELECT * FROM community_profiles';$args=[];if($s!==''){$sql.=' WHERE handle LIKE ? OR name LIKE ?';$args=['%'.ltrim($s,'@').'%','%'.$s.'%'];}$sql.=' ORDER BY created DESC LIMIT 100';return array_values(array_map(fn($p)=>$this->view($p,$who),array_filter($this->q($sql,$args)->fetchAll(),fn($p)=>$p['user_id']===$who||!$this->blocked($who,$p['user_id']))));}
        if($path==='/connections'&&$method==='GET')return array_values(array_map(fn($p)=>$this->view($p,$who),array_filter($this->q('SELECT * FROM community_profiles WHERE user_id<>? ORDER BY created DESC LIMIT 200',[$who])->fetchAll(),fn($p)=>!$this->blocked($who,$p['user_id']))));
        if($path==='/blocks'&&$method==='GET')return $this->q('SELECT p.user_id id,p.handle FROM community_blocks b JOIN community_profiles p ON p.user_id=b.blocked_id WHERE b.user_id=?',[$who])->fetchAll();
        if($path==='/ranking/cities'&&$method==='GET'){$cities=[];foreach($this->q('SELECT p.*,g.payload FROM community_profiles p JOIN community_progress g ON g.user_id=p.user_id WHERE p.ranking_public=1')->fetchAll() as $p){if($this->blocked($who,$p['user_id'])||trim((string)$p['city'])==='')continue;$progress=json_decode($p['payload'],true);if(!is_array($progress)||empty($progress['pointsRankingEligible'])||!is_numeric($progress['points']??null))continue;$key=$this->gymKey($p['city']);if($key==='')continue;if(!isset($cities[$key]))$cities[$key]=['name'=>trim((string)$p['city']),'participants'=>0];$cities[$key]['participants']++;}usort($cities,fn($a,$b)=>strnatcasecmp($a['name'],$b['name']));return['cities'=>array_values($cities)];}
        if($path==='/ranking'&&$method==='GET')return $this->board($who,(string)($_GET['scope']??'friends'),max(0,(int)($_GET['offset']??0)),$mine,(string)($_GET['city']??''));
        if($path==='/achievements/sync'&&$method==='PUT')return $this->syncPersonalAchievements($who,is_array($data['achievements']??null)?$data['achievements']:[]);
        if($path==='/achievement-rarities'&&$method==='GET'){$rows=$this->q('SELECT DISTINCT definition_id FROM community_achievements WHERE definition_id IS NOT NULL LIMIT 500')->fetchAll();$result=[];foreach($rows as $row)$result[$row['definition_id']]=$this->rarity($row['definition_id']);return['rarities'=>$result];}
        if($path==='/achievement-feed'&&$method==='GET'){$scope=(string)($_GET['scope']??'public');$offset=max(0,(int)($_GET['offset']??0));if(!in_array($scope,['public','following'],true))$this->bad(400,'Scope not valid.');$access=$scope==='public'?"p.achievements_visibility='public'":"(a.user_id=? OR (EXISTS(SELECT 1 FROM community_follows f WHERE f.follower_id=? AND f.followed_id=a.user_id) AND (p.achievements_visibility='public' OR (p.achievements_visibility='friends' AND EXISTS(SELECT 1 FROM community_follows back WHERE back.follower_id=a.user_id AND back.followed_id=?)))))";$args=$scope==='public'?[]:[$who,$who,$who];$sql='SELECT a.*,p.handle,p.name,(SELECT COUNT(*) FROM community_achievement_likes l WHERE l.achievement_id=a.id) likes,EXISTS(SELECT 1 FROM community_achievement_likes l WHERE l.achievement_id=a.id AND l.user_id=?) liked FROM community_achievements a JOIN community_profiles p ON p.user_id=a.user_id WHERE '.$access.' AND NOT EXISTS(SELECT 1 FROM community_blocks b WHERE (b.user_id=? AND b.blocked_id=a.user_id) OR (b.user_id=a.user_id AND b.blocked_id=?)) ORDER BY a.created DESC LIMIT 21 OFFSET '.$offset;array_unshift($args,$who);$args[]=$who;$args[]=$who;$rows=$this->q($sql,$args)->fetchAll();$more=count($rows)>20;if($more)array_pop($rows);return['achievements'=>array_map(fn($r)=>$this->achievement($r,$who),$rows),'next'=>$more?$offset+20:null];}
        if($path==='/me/achievement-privacy'&&$method==='PATCH'){$visibility=$data['visibility']??null;if(!in_array($visibility,['private','friends','public'],true))$this->bad(400,'Revisa quién puede ver tus logros.');$this->q('UPDATE community_profiles SET achievements_public=?,achievements_visibility=? WHERE user_id=?',[(int)($visibility!=='private'),$visibility,$who]);return $this->view($this->profile($who,''),$who);}
        if(preg_match('#^/profiles/([a-f0-9]{32})/achievements$#i',$path,$m)&&$method==='GET'){if(!$this->canAchievements($m[1],$who))$this->bad(403,'Estos logros son privados.');$rows=$this->q('SELECT a.*,p.handle,p.name,(SELECT COUNT(*) FROM community_achievement_likes l WHERE l.achievement_id=a.id) likes,EXISTS(SELECT 1 FROM community_achievement_likes l WHERE l.achievement_id=a.id AND l.user_id=?) liked FROM community_achievements a JOIN community_profiles p ON p.user_id=a.user_id WHERE a.user_id=? ORDER BY a.created DESC LIMIT 200',[$who,$m[1]])->fetchAll();return['achievements'=>array_map(fn($r)=>$this->achievement($r,$who),$rows),'next'=>null];}
        if($path==='/achievements'&&$method==='GET'){$owner=(string)($_GET['user']??'');$following=(string)($_GET['following']??'');$offset=max(0,(int)($_GET['offset']??0));$where=['(a.user_id=? OR (p.achievements_public=1 AND p.progress_visibility=\'public\'))'];$args=[$who];if($owner!==''){$where[]='a.user_id=?';$args[]=$owner;}if($following==='1'){$where[]='(a.user_id=? OR EXISTS(SELECT 1 FROM community_follows f WHERE f.follower_id=? AND f.followed_id=a.user_id))';$args[]=$who;$args[]=$who;}$sql='SELECT a.*,p.handle,p.name,(SELECT COUNT(*) FROM community_achievement_likes l WHERE l.achievement_id=a.id) likes,EXISTS(SELECT 1 FROM community_achievement_likes l WHERE l.achievement_id=a.id AND l.user_id=?) liked FROM community_achievements a JOIN community_profiles p ON p.user_id=a.user_id WHERE '.implode(' AND ',$where).' ORDER BY a.created DESC LIMIT 21 OFFSET '.$offset;array_unshift($args,$who);$rows=$this->q($sql,$args)->fetchAll();$more=count($rows)>20;if($more)array_pop($rows);return['achievements'=>array_map(fn($r)=>$this->achievement($r,$who),$rows),'next'=>$more?$offset+20:null];}
        if(preg_match('#^/achievements/([a-f0-9]{32})/like$#i',$path,$m)&&in_array($method,['PUT','DELETE'],true)){$a=$this->q('SELECT a.*,p.handle,p.name FROM community_achievements a JOIN community_profiles p ON p.user_id=a.user_id WHERE a.id=?',[$m[1]])->fetch();if(!$a||!$this->canAchievements($a['user_id'],$who))$this->bad(404,'Logro no encontrado.');if($method==='PUT')$this->q('INSERT IGNORE INTO community_achievement_likes(achievement_id,user_id,created)VALUES(?,?,?)',[$m[1],$who,time()]);else$this->q('DELETE FROM community_achievement_likes WHERE achievement_id=? AND user_id=?',[$m[1],$who]);return['ok'=>true];}
        if($path==='/notification-preferences/achievements'&&$method==='GET'){$r=$this->q('SELECT achievement_likes FROM community_notification_preferences WHERE user_id=?',[$who])->fetch();return['achievementLikes'=>$r?((int)$r['achievement_likes']===1):true];}
        if($path==='/notification-preferences/achievements'&&$method==='PATCH'){$value=$data['achievementLikes']??null;if(!is_bool($value))$this->bad(400,'Revisa las notificaciones de felicitaciones.');$this->q('INSERT INTO community_notification_preferences(user_id,achievement_likes)VALUES(?,?) ON DUPLICATE KEY UPDATE achievement_likes=VALUES(achievement_likes)',[$who,(int)$value]);return['achievementLikes'=>$value];}
        if($path==='/me/notification-preferences'&&$method==='GET'){$r=$this->q('SELECT achievement_likes FROM community_notification_preferences WHERE user_id=?',[$who])->fetch();return['achievementLikes'=>$r?((int)$r['achievement_likes']===1):true];}
        if($path==='/me/notification-preferences'&&$method==='PATCH'){$value=$data['achievementLikes']??null;if(!is_bool($value))$this->bad(400,'Revisa las notificaciones de felicitaciones.');$this->q('INSERT INTO community_notification_preferences(user_id,achievement_likes)VALUES(?,?) ON DUPLICATE KEY UPDATE achievement_likes=VALUES(achievement_likes)',[$who,(int)$value]);return['achievementLikes'=>$value];}
        if($path==='/machine-brands'&&$method==='GET'){$exercise=$this->txt((string)($_GET['exercise']??''),80,true);$gym=$mine['gym_id']??'';$gymRows=$gym!==''?$this->q('SELECT brand FROM community_machine_brands WHERE gym_id=? AND exercise_id=? ORDER BY uses DESC,brand',[$gym,$exercise])->fetchAll():[];$global=$this->q('SELECT brand FROM community_machine_brands WHERE exercise_id=? ORDER BY uses DESC,brand LIMIT 100',[$exercise])->fetchAll();return['gym'=>array_values(array_unique(array_column($gymRows,'brand'))),'global'=>array_values(array_unique(array_column($global,'brand')))];}
        if($path==='/machine-brands'&&$method==='POST'){$exercise=$this->txt($data['exerciseId']??'',80,true);$brand=$this->txt($data['brand']??'',60,true);$gym=$mine['gym_id']??'';$this->q('INSERT INTO community_machine_brands(gym_id,exercise_id,brand,uses,updated)VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE uses=uses+1,updated=VALUES(updated)',[$gym,$exercise,$brand,1,time()]);return['ok'=>true];}
        if($path==='/exercise-proposals'&&$method==='POST'){$name=$this->txt($data['name']??'',120,true);$this->q('INSERT INTO community_exercise_proposals(id,user_id,name,payload,created)VALUES(?,?,?,?,?)',[$this->id(),$who,$name,json_encode($data,JSON_UNESCAPED_UNICODE),time()]);return['ok'=>true];}
        if($path==='/me/trainer-profile'&&$method==='PUT'){$specialties=$data['specialties']??[];$modalities=$data['modalities']??[];if(!is_array($specialties)||!is_array($modalities))$this->bad(400,'Revisa el perfil profesional.');$public=$this->yes($data['public']??false);$stats=$this->yes($data['statsPublic']??false);$years=max(0,min(100,(int)($data['experienceYears']??0)));$this->q('INSERT INTO community_trainer_profiles(user_id,public,specialties,modalities,experience_years,credentials,availability,pricing,stats_public,updated)VALUES(?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE public=VALUES(public),specialties=VALUES(specialties),modalities=VALUES(modalities),experience_years=VALUES(experience_years),credentials=VALUES(credentials),availability=VALUES(availability),pricing=VALUES(pricing),stats_public=VALUES(stats_public),updated=VALUES(updated)',[$who,$public,json_encode(array_values($specialties)),json_encode(array_values($modalities)),$years,$this->txt($data['credentials']??'',500),$this->txt($data['availability']??'',160),$this->txt($data['pricing']??'',160),$stats,time()]);$p=$this->q('SELECT * FROM community_trainer_profiles WHERE user_id=?',[$who])->fetch();return['public'=>(bool)$p['public'],'specialties'=>json_decode($p['specialties'],true)?:[],'modalities'=>json_decode($p['modalities'],true)?:[],'experienceYears'=>(int)$p['experience_years'],'credentials'=>$p['credentials'],'availability'=>$p['availability'],'pricing'=>$p['pricing'],'statsPublic'=>(bool)$p['stats_public'],'updated'=>gmdate('c',$p['updated'])];}
        if(preg_match('#^/profiles/([a-f0-9]{32})/trainer$#i',$path,$m)&&$method==='GET'){$p=$this->q('SELECT * FROM community_trainer_profiles WHERE user_id=?',[$m[1]])->fetch();if(!$p||(!$p['public']&&$m[1]!==$who))$this->bad(404,'Perfil profesional no disponible.');return['public'=>(bool)$p['public'],'specialties'=>json_decode($p['specialties'],true)?:[],'modalities'=>json_decode($p['modalities'],true)?:[],'experienceYears'=>(int)$p['experience_years'],'credentials'=>$p['credentials'],'availability'=>$p['availability'],'pricing'=>$p['pricing'],'statsPublic'=>(bool)$p['stats_public'],'updated'=>gmdate('c',$p['updated'])];}
        if($path==='/gyms'&&$method==='GET'){ $q=$this->gymKey($this->txt((string)($_GET['q']??''),120));$city=$this->gymKey($this->txt((string)($_GET['city']??''),120));$rows=$this->q("SELECT id,'manual' provider,name,'' address,city,'active' status FROM community_gyms ORDER BY name LIMIT 200")->fetchAll();return array_values(array_filter($rows,fn($g)=>($q===''||str_contains($this->gymKey($g['name']),$q))&&($city===''||$this->gymKey($g['city'])===$city)));}
        if($path==='/gyms'&&$method==='POST'){$name=$this->txt($data['name']??'',120,true);$city=$this->txt($data['city']??'',120);$nameKey=$this->gymKey($name);$cityKey=$this->gymKey($city);$g=null;foreach($this->q('SELECT * FROM community_gyms ORDER BY created ASC LIMIT 500')->fetchAll() as $candidate){if($this->gymKey($candidate['name'])===$nameKey&&$this->gymKey($candidate['city'])===$cityKey){$g=$candidate;break;}}if(!$g){$g=['id'=>$this->id(),'name'=>$name,'city'=>$city];$this->q('INSERT INTO community_gyms(id,name,city,created)VALUES(?,?,?,?)',[$g['id'],$name,$city,time()]);}return['id'=>$g['id'],'provider'=>'manual','name'=>$g['name'],'address'=>'','city'=>$g['city'],'status'=>'active'];}
        if($path==='/posts'&&$method==='POST'){$caption=$this->txt($data['caption']??'',500,true);$id=$this->id();$this->q('INSERT INTO community_posts(id,user_id,caption,created)VALUES(?,?,?,?)',[$id,$who,$caption,time()]);return['id'=>$id];}
        if($path==='/posts'&&$method==='GET'){$following=(string)($_GET['following']??'')==='1';$owner=(string)($_GET['user']??'');$offset=max(0,(int)($_GET['offset']??0));$sql='SELECT p.*,u.handle,u.name,(SELECT COUNT(*) FROM community_post_likes l WHERE l.post_id=p.id) likes FROM community_posts p JOIN community_profiles u ON u.user_id=p.user_id';$args=[];$where=[];if($owner!==''){$where[]='p.user_id=?';$args[]=$owner;}if($following){$where[]='EXISTS(SELECT 1 FROM community_follows f WHERE f.follower_id=? AND f.followed_id=p.user_id)';$args[]=$who;}if($where)$sql.=' WHERE '.implode(' AND ',$where);$sql.=' ORDER BY p.created DESC LIMIT 21 OFFSET '.$offset;$rows=array_values(array_filter($this->q($sql,$args)->fetchAll(),fn($r)=>!$this->blocked($who,$r['user_id'])));$more=count($rows)>20;if($more)array_pop($rows);return['posts'=>array_map(fn($r)=>$this->post($r,$who),$rows),'next'=>$more?$offset+20:null];}
        if(preg_match('#^/posts/([a-f0-9]{32})/like$#i',$path,$m)&&in_array($method,['PUT','DELETE'],true)){if($method==='PUT')$this->q('INSERT IGNORE INTO community_post_likes(post_id,user_id,created)VALUES(?,?,?)',[$m[1],$who,time()]);else$this->q('DELETE FROM community_post_likes WHERE post_id=? AND user_id=?',[$m[1],$who]);return['ok'=>true];}
        if(preg_match('#^/posts/([a-f0-9]{32})$#i',$path,$m)&&$method==='DELETE'){$this->q('DELETE FROM community_posts WHERE id=? AND user_id=?',[$m[1],$who]);return['ok'=>true];}
        if(preg_match('#^/follow/([a-f0-9]{32})$#i',$path,$m)&&in_array($method,['PUT','DELETE'],true)){$target=$m[1];if($target===$who||!$this->q('SELECT 1 FROM community_profiles WHERE user_id=?',[$target])->fetch()||$this->blocked($who,$target))$this->bad(400,'No se puede seguir a esta persona.');if($method==='PUT'){$follow=$this->q('INSERT IGNORE INTO community_follows(follower_id,followed_id,created)VALUES(?,?,?)',[$who,$target,time()]);if($follow->rowCount())$this->q('INSERT IGNORE INTO community_notifications(id,recipient_id,actor_id,type,created)VALUES(?,?,?,?,?)',[$this->id(),$target,$who,'follow',time()]);}else$this->q('DELETE FROM community_follows WHERE follower_id=? AND followed_id=?',[$who,$target]);return$this->view($this->profile($target,''),$who);}
        if($path==='/notifications'&&$method==='GET'){return $this->q('SELECT n.id,n.type,n.created,n.read_at,p.user_id actorId,p.handle,p.name,p.avatar FROM community_notifications n JOIN community_profiles p ON p.user_id=n.actor_id WHERE n.recipient_id=? ORDER BY n.created DESC LIMIT 30',[$who])->fetchAll();}
        if($path==='/notifications/read'&&$method==='PATCH'){$this->q('UPDATE community_notifications SET read_at=? WHERE recipient_id=? AND read_at IS NULL',[time(),$who]);return['ok'=>true];}
        if(preg_match('#^/blocks/([a-f0-9]{32})$#i',$path,$m)&&in_array($method,['PUT','DELETE'],true)){$target=$m[1];if($target===$who)$this->bad(400,'No puedes bloquearte.');if($method==='PUT'){$this->q('INSERT IGNORE INTO community_blocks(user_id,blocked_id,created)VALUES(?,?,?)',[$who,$target,time()]);$this->q('DELETE FROM community_follows WHERE (follower_id=? AND followed_id=?) OR (follower_id=? AND followed_id=?)',[$who,$target,$target,$who]);}else$this->q('DELETE FROM community_blocks WHERE user_id=? AND blocked_id=?',[$who,$target]);return['ok'=>true];}
        if(in_array($path,['/reports','/profile-reports'],true)&&$method==='POST'){$target=$this->txt($data[$path==='/reports'?'postId':'userId']??'',64,true);$reason=$this->txt($data['reason']??'',500,true);$this->q('INSERT INTO community_reports(id,reporter_id,target_type,target_id,reason,created)VALUES(?,?,?,?,?,?)',[$this->id(),$who,$path==='/reports'?'post':'profile',$target,$reason,time()]);return['ok'=>true];}
        if($path==='/coaching/progress/me'&&$method==='PUT'){$this->q('CREATE TABLE IF NOT EXISTS community_coaching_progress (client_id VARCHAR(64) NOT NULL,trainer_id VARCHAR(64) NOT NULL,payload MEDIUMTEXT NOT NULL,updated BIGINT NOT NULL,PRIMARY KEY(client_id,trainer_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');$trainers=$this->q("SELECT trainer_id FROM community_coaching WHERE client_id=? AND status='active'",[$who])->fetchAll();foreach($trainers as $row)$this->q('INSERT INTO community_coaching_progress(client_id,trainer_id,payload,updated)VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE payload=VALUES(payload),updated=VALUES(updated)',[$who,$row['trainer_id'],json_encode($data,JSON_UNESCAPED_UNICODE),time()]);return['ok'=>true];}
        if($path==='/coaching'&&$method==='GET'){$rows=$this->q('SELECT c.*,p.user_id,p.handle,p.name,p.avatar,COALESCE(s.enabled,0) stats_consent FROM community_coaching c JOIN community_profiles p ON p.user_id=IF(c.client_id=?,c.trainer_id,c.client_id) LEFT JOIN community_coaching_stats_consent s ON s.client_id=c.client_id AND s.trainer_id=c.trainer_id WHERE c.client_id=? OR c.trainer_id=? ORDER BY c.updated DESC',[$who,$who,$who])->fetchAll();return array_map(function($r)use($who){$permissions=$this->trainerPermissions($r['id']);return['id'=>$r['id'],'status'=>$r['status'],'role'=>$r['trainer_id']===$who?'trainer':'client','requestedByMe'=>($r['requested_by']??$r['trainer_id'])===$who,'statsConsent'=>(bool)$r['stats_consent'],'permissions'=>$permissions,'created'=>gmdate('c',$r['created']),'acceptedAt'=>$r['accepted']?gmdate('c',(int)$r['accepted']):null,'endedAt'=>$r['ended']?gmdate('c',(int)$r['ended']):null,'updated'=>gmdate('c',$r['updated']),'person'=>['id'=>$r['user_id'],'handle'=>$r['handle'],'name'=>$r['name'],'avatar'=>$r['avatar']]];},$rows);}
        if($path==='/coaching/requests'&&$method==='POST'){$client=$this->txt($data['targetId']??'',64,true);if($client===$who||!$this->q('SELECT 1 FROM community_profiles WHERE user_id=?',[$client])->fetch())$this->bad(400,'No se puede solicitar colaboración.');$now=time();$this->q("INSERT INTO community_coaching(id,client_id,trainer_id,status,created,updated)VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE status='pending',updated=VALUES(updated)",[$this->id(),$client,$who,'pending',$now,$now]);return['ok'=>true];}
        if(preg_match('#^/coaching/([a-f0-9]{32})$#i',$path,$m)&&$method==='PATCH'){$r=$this->coach($m[1],$who);$a=$data['action']??'';if($a==='accept'&&$r['status']==='pending'&&($r['requested_by']??$r['trainer_id'])!==$who){$this->q("UPDATE community_coaching SET status='active',accepted=?,updated=? WHERE id=?",[time(),time(),$m[1]]);}elseif($a==='decline'&&$r['status']==='pending')$this->q("UPDATE community_coaching SET status='declined',ended=?,updated=? WHERE id=?",[time(),time(),$m[1]]);elseif($a==='revoke'&&$r['status']==='active'){$this->q('DELETE FROM community_coaching_progress WHERE client_id=? AND trainer_id=?',[$r['client_id'],$r['trainer_id']]);$this->q("UPDATE community_coaching SET status='revoked',ended=?,revoked_by=?,updated=? WHERE id=?",[time(),$who,time(),$m[1]]);}else$this->bad(400,'Acción de colaboración no válida.');return['ok'=>true];}
        if($path==='/coaching/routine/me'&&$method==='PUT'){$rows=$this->q("SELECT * FROM community_coaching WHERE client_id=? AND status='active' ORDER BY updated DESC",[$who])->fetchAll();if(!$rows)$this->bad(403,'No tienes una colaboración activa.');foreach($rows as $r)$this->q('INSERT INTO community_coaching_routines(coaching_id,payload,revision,updated,author_id)VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE payload=VALUES(payload),revision=revision+1,updated=VALUES(updated),author_id=VALUES(author_id)',[$r['id'],json_encode($data,JSON_UNESCAPED_UNICODE),1,time(),$who]);return['ok'=>true];}
        if(preg_match('#^/coaching/([a-f0-9]{32})/routine$#i',$path,$m)&&in_array($method,['GET','PUT'],true)){$r=$this->coach($m[1],$who);if($r['status']!=='active'||!$this->trainerPermissions($m[1])['routine'])$this->bad(403,'La gestión de rutina no está autorizada.');if($method==='PUT'){if($r['trainer_id']!==$who)$this->bad(403,'Solo el entrenador puede modificar esta rutina.');$this->q('INSERT INTO community_coaching_routines(coaching_id,payload,revision,updated,author_id)VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE payload=VALUES(payload),revision=revision+1,updated=VALUES(updated),author_id=VALUES(author_id)',[$m[1],json_encode($data,JSON_UNESCAPED_UNICODE),1,time(),$who]);}$managed=$this->q('SELECT * FROM community_coaching_routines WHERE coaching_id=?',[$m[1]])->fetch();if(!$managed)$this->bad(404,'La rutina aún no está disponible.');$author=$this->profile($managed['author_id'],'');return['routine'=>json_decode($managed['payload'],true),'revision'=>(int)$managed['revision'],'updated'=>gmdate('c',$managed['updated']),'author'=>['id'=>$author['user_id'],'handle'=>$author['handle'],'name'=>$author['name']]];}
        if($path==='/profiles'&&$method==='GET'){
            $query=mb_strtolower(ltrim((string)($_GET['q']??''),'@'),'UTF-8');
            $term='%'.$query.'%';
            $rows=$this->q('SELECT * FROM community_profiles WHERE LOWER(handle) LIKE ? OR LOWER(name) LIKE ? ORDER BY handle LIMIT 30',[$term,$term])->fetchAll();
            return array_values(array_map(fn($p)=>$this->view($p,$who),array_filter($rows,fn($p)=>!$this->blocked($who,$p['user_id']))));
        }
        if($path==='/connections'&&$method==='GET'){
            $rows=$this->q('SELECT p.* FROM community_profiles p WHERE p.user_id IN (SELECT followed_id FROM community_follows WHERE follower_id=?) OR p.user_id IN (SELECT follower_id FROM community_follows WHERE followed_id=?) ORDER BY p.handle LIMIT 100',[$who,$who])->fetchAll();
            return array_values(array_map(fn($p)=>$this->view($p,$who),array_filter($rows,fn($p)=>!$this->blocked($who,$p['user_id']))));
        }
        if(preg_match('#^/profiles/([a-f0-9]{32})/(followers|following)$#i',$path,$m)&&$method==='GET'){$sql=$m[2]==='followers'?'SELECT p.* FROM community_follows f JOIN community_profiles p ON p.user_id=f.follower_id WHERE f.followed_id=?':'SELECT p.* FROM community_follows f JOIN community_profiles p ON p.user_id=f.followed_id WHERE f.user_id=?';return array_values(array_map(fn($p)=>$this->view($p,$who),array_filter($this->q($sql,[$m[1]])->fetchAll(),fn($p)=>!$this->blocked($who,$p['user_id']))));}
        if(preg_match('#^/profiles/([a-f0-9]{32})/progress$#i',$path,$m)&&$method==='GET'){$p=$this->profile($m[1],'');if(!($m[1]===$who||$p['progress_visibility']==='public'||($p['progress_visibility']==='friends'&&$this->connected($who,$m[1]))))$this->bad(403,'Este progreso es privado o solo está disponible entre seguidores mutuos.');$r=$this->q('SELECT payload FROM community_progress WHERE user_id=?',[$m[1]])->fetch();if(!$r)$this->bad(404,'Progreso no disponible.');return json_decode($r['payload'],true);}
        if(preg_match('#^/routines/([a-f0-9]{32})$#i',$path,$m)&&$method==='GET'){$p=$this->profile($m[1],'');if(!($m[1]===$who||$p['progress_visibility']==='public'||($p['progress_visibility']==='friends'&&$this->connected($who,$m[1]))))$this->bad(403,'Esta rutina es privada o solo está disponible entre seguidores mutuos.');$r=$this->q('SELECT payload,updated FROM community_routines WHERE user_id=?',[$m[1]])->fetch();if(!$r)$this->bad(404,'Rutina no disponible.');return['id'=>$m[1],'owner'=>['handle'=>$p['handle'],'name'=>$p['name']],'routine'=>json_decode($r['payload'],true),'updated'=>$r['updated']];}
        if(preg_match('#^/profiles/([a-f0-9]{32})$#i',$path,$m)&&$method==='GET'){if($this->blocked($who,$m[1]))$this->bad(404,'Perfil no encontrado.');return$this->view($this->profile($m[1],''),$who);}
        $this->bad(404,'Ruta de Comunidad no disponible.');
    }
}
